### ISSUE TITLE
Test Run sharing -> users may share their Test Runs to Mojaloop community.

### ISSUE THREAD

**Issue by agalaguz** [gsmainclusivetechlab/interop-test-platform#111]
If User find some Mojaloop error in Test Case, he may need to share it with Mojaloop community.

So, that we may have some "Share" or "Make Public" button that make Test Run visible for everyone.

**Comment by brunosmm** [comment]
Test Run is visible to anyone who has the shared URL, should not be listed in sessions pages.
Information to execute a test case in the session should not be display.
