### ISSUE TITLE
Test Case -> after moving from Overview tab's "Test Run screen" to other tabs, I can't return to "Test Run screen" by clicking on Overview tab.

### ISSUE THREAD

**Issue by agalaguz** [gsmainclusivetechlab/interop-test-platform#112]
After moving from Overview tab's "Test Run screen" to other tabs, I can't return to "Test Run screen" by clicking on Overview tab.

Steps to reproduce:

1) Find any Test Case that have at least 1 Test Run and go to this Test Case page.
2) Click on Test Run https://prnt.sc/s6smo9
3) Note that you are on Test Run screen https://prnt.sc/s6snoo
3) Click on Test Steps or Flow tabs https://prnt.sc/s6smy6
4) From Test Steps click on Overview https://prnt.sc/s6sn5s

Actual Result: I see the list of Test Runs https://prnt.sc/s6sng0
Expected Result: I see Test Run https://prnt.sc/s6snoo as I didn't close it by clicking on <Run https://prnt.sc/s6stez

**Comment by agalaguz** [comment]
@eudisley @brunosmm 
Hey guys, sorry for getting back to it one more time -> we found a similar UI even in github that I would like to describe. 
It is here, in issues of GH https://github.com/gsmainclusivetechlab/interop-test-platform/issues and it behaves exactly the same way as Test Run list/single page. So, the steps are next:
1. Go to [issues list](http://prntscr.com/spb2c7). (it is like a Test Runs list)
2. Click on [any isssue](http://prntscr.com/spb3gm) and see [its page](http://prntscr.com/spb3vs). (it's like a Test Run single page) 
3. Go click on '[Pull requests](http://prntscr.com/spb4hd)' or any other tab. (it's like clicking on Flow or other tabs)
4. From '[Pull requests](http://prntscr.com/spb5hx)' click 'Issues' and you will see the [list of Issues](http://prntscr.com/spb65u) instead of the issue I came from. (it's like now we are getting back to Test Run list instead of Test Run single page)

I'm just trying to describe that it is a common tab behavior and adding the unusual behavior also adds a bit of complexity. Maybe a miss of ability to reach a single Test Run from other tabs is rather UX/UI problem so, it can be reviewed a bit... 
We can dig into vue controllers to implement the described behavior, but not sure it can be done within this sprint...

**Comment by eudisley** [comment]
Looking in the JC staging version I think everything looks ok to me. The problem we had before was not about the tabs but about the arrow ( < ) we have in a test next to Run ID. Previously it was not going back to the test list, if I am not wrong. Thus, in my point of view it is good how it is working now.

**Comment by brunosmm** [comment]
So means no changes need, we can close this.
