### ISSUE TITLE
Rejected Quote by Payee FSP - Step 8 - PUT quotes ID error

### ISSUE THREAD

**Issue by vmartynov** [gsmainclusivetechlab/interop-test-platform#117]
body.errorInformation.errorDescription is not beibg sent by MMO1 simulator
This field is required according to documentation
https://github.com/gsmainclusivetechlab/interop-test-platform/blob/develop/src/database/seeds/openapi/mojaloop.yaml

https://prnt.sc/s83ocj

**Comment by brunosmm** [comment]
Hey @vmartynov / @jc-skushnir,

Is this issue still happening?

**Comment by vmartynov** [comment]
Hi @brunosmm 
It is fixed, closing this.
