### ISSUE TITLE
Create Test Cases for P2P - Happy Flow

### ISSUE THREAD

**Issue by brunosmm** [gsmainclusivetechlab/interop-test-platform#123]

**Comment by eudisley** [comment]
All test cases for Happy Flows are finished and under test by Anton.
I will create another Issue for P2P Unhappy Flow to get more organised.

**Comment by eudisley** [comment]
Test Cases created:
P2P0100, P2P0200, P2P0300, P2P0400, P2P0500, P2P0600, P2P0700, P2P0800
