### ISSUE TITLE
Create Test Case documentation for tutorial

### ISSUE THREAD

**Issue by brunosmm** [gsmainclusivetechlab/interop-test-platform#127]
The main idea is how to write a YAML file

**Comment by eudisley** [comment]
The tutorial is finished and passed for MD file. I think we should review the English and add more text to make it easier to understand. @SamyBouch may you do this review, please? the file is called tctemplate.md

**Comment by SamyBouch** [comment]
@eudisley Brilliant, sure I will have a look at it today.
