### ISSUE TITLE
Asign Test Cases to a group of users

### ISSUE THREAD

**Issue by brunosmm** [gsmainclusivetechlab/interop-test-platform#134]
As Test Creator role or Admin, I want to be able to assign a test case to a user group. 

Tasks:

- [ ] UI
- [ ] Implementation

Requirements:

- Admin will be able to choose any user group to the test case;
- Test Creator is able to assign only the user group he belongs if he belongs to some.

Open Points:

- Should be possible to assign more than one user group to a test case?

**Comment by agalaguz** [comment]
Hi, Could you please add more context to this task?
What is the reason for an Admin/TC Creator to assign groups to a Test Case and what benefits will they get from it? 
I guess this is a way to create Test Cases that are visible for specific Users/Groups, _e.g. John Smith and Safaricom members can see and use "Merchant payment Receive type"_. If you provide us with some more examples, it would be helpful.

**Comment by brunosmm** [comment]
Hi Anton,

Yes, that's the intention! So if a group of users want to create a test case we don't want to make it available straight after the creation, so will be only visible for the group of the test creator, also somre group of users has specific needs which does not make sense to others, so we do not create a huge set of test cases to everyone.
Later admins can change it.
