### ISSUE TITLE
Test Run chart displaying in wrong chronological order

### ISSUE THREAD

**Issue by brunosmm** [gsmainclusivetechlab/interop-test-platform#206]
As you can see in the image below May 29 should be the starting of the chart, doing asc date order.

![image](https://user-images.githubusercontent.com/1554850/83524156-1710ee00-a4db-11ea-9098-a87887db5591.png)

**Comment by jcakokorev** [comment]
@brunosmm i think you just need to change in this row https://github.com/gsmainclusivetechlab/interop-test-platform/blob/master/src/app/Http/Controllers/Sessions/SessionController.php#L150 ASC to DESC
