### ISSUE TITLE
Notice Pop-Up Should Automatically Disappear  

### ISSUE THREAD

**Issue by eudisley** [gsmainclusivetechlab/interop-test-platform#214]
The notice pop-up when we import a new test case is disappearing only when we click on it. I consider it would be better for the UI if it would disappear after some seconds. Maybe about 3 or 4 seconds. 

I am attaching a picture to show the pop-up I am talking about. Maybe it would be good to check if there are others with the same problem. 

![Screen Shot 2020-06-08 at 13 14 34](https://user-images.githubusercontent.com/4050924/84067329-a9166c00-a99d-11ea-9b9c-afa195a9cfcd.png)

![Screen Shot 2020-06-08 at 13 18 37](https://user-images.githubusercontent.com/4050924/84067402-c2b7b380-a99d-11ea-9db1-3242b7aad076.png)

**Comment by cjol** [comment]
I agree, I have noticed this before and it is quite annoying!

**Comment by jcakokorev** [comment]
@cjol seems like we forgot about adding "timeout" option to Noty after migrating to hybrid SPA. You can simply add "timeout" option here https://github.com/gsmainclusivetechlab/interop-test-platform/blob/master/src/resources/js/layouts/app.vue#L60 like "timeout: 3000" etc. (https://ned.im/noty/#/options)
