### ISSUE TITLE
Token Substitution in other test_step fields

### ISSUE THREAD

**Issue by cjol** [gsmainclusivetechlab/interop-test-platform#233]
Currently, token substitution (e.g. `SP_BASE_URI`) only occurs in one location - the example `request` field, which is used in the first step of any test case to trigger a test run execution through the test platform. It would be useful to apply it in all other locations. Some locations which are currently not substituted:

 - Request/response examples when displayed in the test platform
 - Overrides in `test_request_setups` and `test_response_setups`
 - Assertions in `test_request_scripts` and `test_response_scripts` (although this might be messy because Laravel currently parses these assertions directly).
 - Other `test_step` common values (e.g. `path`, `trigger` or `pattern`)

cc: @brunosmm we previously discussed the first bullet above, but there are other locations this would be good to have too.

**Comment by brunosmm** [comment]
Thanks for adding this, fully agree.
Will be easier to explode each bullet in diff issues so we can prioritize it.
