### ISSUE TITLE
Test Case Managment

### ISSUE THREAD

**Issue by brunosmm** [gsmainclusivetechlab/interop-test-platform#240]
As a Test Creator role or Admin role, I want to be able to see, edit, add, delete and clone test cases using the UI. Versioning should be created to ensure we can keep history.

Task:

- [ ] Define User Experience
- [ ] Create UI
- [ ] Create test case versioning model
- [ ] Implementation 

Requirements:

- Versioning:
  - Test Case Name should be Unique in the entire system;
  - Test Case Edit always generate a new version of the test case;
  - Once a new version is created, should offer the option for people using this test case in a session to upgrade to the new version. More details will be set in a separate issue.
  - Audit log should be created to keep a record of what, who and when data was changed in the test case.
    - Can be split into parts, initially record only who and when and later what.

- Edit:
  - Blocking to change main information such as Name, Use Case, Components, Behaviour.
  - If the test case is not public, the edit does not generate a new version.
  - If the test case is public:
    - If it's linked with a session, a new version should be created.
    - if is not linked with a session, the edit should store the data in the same session.

- Delete:
  - If the test case is linked with a session, should be done a soft delete.
  The test case will continue in the database to be possible to see the information into the session but will not be possible to use this test case in new sessions.
  - If not linked, full delete from the database will be done.
  - Once a session is deleted, should execute a DB check for soft-deleted test cases, if they are not linked with a session anymore should be purge from the database.

- Clone:
  - Should copy all the data from the test case, and set the test case name to be blank.

**Comment by eudisley** [comment]
I think this option: _If the test case is linked with a session, should be done a soft delete._ is more like another function, such as disable / enable test cases.

**Comment by brunosmm** [comment]
Enable and disable we already have, which is the public/non-public.
Deletion to remove, but sometimes not possible to erase because has results attached to it.

**Comment by cjol** [comment]
Closing in favour of #281 and other more focussed issues coming soon.
