### ISSUE TITLE
Components Manager

### ISSUE THREAD

**Issue by brunosmm** [gsmainclusivetechlab/interop-test-platform#242]
As an Admin role, I want to be able to see, edit, add and delete components using the UI. 

Tasks:

- [ ] Create UI
- [ ] Implementation 

Requirements:

- UUID should be automatically generated by the platform, no actions from the user.

Open Points:

- Is it possible to components using the same position? What happens on the UI?
- Should be base URL unique between components? Is it make sense having two components with the same URL?

**Comment by agalaguz** [comment]
Hi, could you please advise which new Components you expecting to add? 
Understanding their role, purpose and possible positions in the chain should help us to have a better vision on this feature.

**Comment by brunosmm** [comment]
Hi Anton,

For now, we don't envision other components that we already have. This is mainly to be possible configure all in the screen.
If we want to make Moja as SUT, need to change on the database, with this we can do in the interface.
