### ISSUE TITLE
Certification Sessions

### ISSUE THREAD

**Issue by brunosmm** [gsmainclusivetechlab/interop-test-platform#244]
As an platform user, I want to be able to create a certification session. A Certification session should act as any other session, but the user **cannot** edit the test cases in the session and can only execute each test cases X times, where X is defined in the platform configuration .env.
The certificate session will have a status (different from test results) which will be used to control whether a test can or cannot be executed.

Requirements:

- When creating a session, the user should be able to choose between creating a normal (test) session, or a compliance session.
- The user should not be able to edit compliance session test cases after creation.
- The possible session statuses:
  - Ready: The session starts in this status
  - In Execution: As soon as the first test is executed, the session moves  to this status;
  - In Verification: At some point, the user will manually set the session as "completed". At this point, the status moves to "In verification" and no further test executions are allowed.
  - Approved/Declined: The platform admin will review the session results, and wlil then be able to approve or decline the session. In both cases, the admin will enter a reason for the approval/rejection. After a session has been marked in this way, no possible actions are possible within this session.
 - Once a session enters in "In Verification", "Approved", "Declined" status the system should disable the session execution, which means messages sent to the session URL should be ignored.
 - Execution limits should be defined in the .env file.
 - Before a session can be moved into `In Verification`, the user must be shown a confirmation window to indicate that they know this is a non-reversible action, and that they will need to create a new session if they wish to execute any more test cases.
 - By default, compliance session fields are non-editable after creation. The exceptions are:
  - The user can add/remove environment variables
  - The user can modify the URL of their SUT

**Comment by agalaguz** [comment]
Hi, could you please describe a "business side" of this feature? Not sure about the benefits that Admin will receive from this feature... 
Maybe you have some examples from the other test platforms?

**Comment by brunosmm** [comment]
Rules to Enable the "Session Submission Button":

- Execute at least once all the test cases do not matter the test case result. You CAN submit a session with fail test cases.
- Add a warning to a test case before reach the max execution on the test case, if can execute 5 times, show a warning once reach more than 50% of the execution times, in this example, 3.
