### ISSUE TITLE
Session Environments

### ISSUE THREAD

**Issue by brunosmm** [gsmainclusivetechlab/interop-test-platform#245]
**New concept: Session Environments**
A session environment is a key-value store of custom user data. This data is used to customise the execution of test cases within the session. For example, the data may be substituted into the initial request (#273). Alternatively, it may be used to encrypt/decrypt messages transmitted through the test platform.

**User Story**
As a platform user, I want to be able to create an environment and set data so that the execution flow of the session is customised to my needs.

**Requirements**
- Any user can create an environment at the same time as a test session is being created. This environment will be only visible to the user and not shared with others.
- Each environment variable is entered through two text fields - one for the "key" and one for the "value". All environment variables are stored as strings.
- A global list of "expected" keys should be centrally defined. These keys will be shown by default when creating a session environment. 

Related issues:
#273 - Advanced Token Substitution. The variables defined in this environment will be used for substitution. 
#233 - Substituting Variables In other places of the test. This starts to give an indication of other ways in which environment variables might be used. 
#274  - Group Environments will extend Session Environments with shared data.
#275  - Test case definitions will be scanned to identify variables in use and prepopulate the "keys" for a session environment.

**Comment by agalaguz** [comment]
Hi, could you please provide us with examples of data that should be configured in environments?

- SUT selection (SP, MMO1, etc)
- SUT URL
- Session name/description 
- Selected test cases

anything else?

**Comment by brunosmm** [comment]
Hi Anton,

This is a new set of data which will be possible to use, looking as Key Pairs(like a map) feature.
This will hold information for further features such as encryption keys and use those variables in the test case, inside request example and assertions.
body.amount = ${GLOBAL_AMOUNT} and GLOBAL_AMOUNT is a variable inside the envrionment.
