### ISSUE TITLE
Show email address on user profile page

### ISSUE THREAD

**Issue by cjol** [gsmainclusivetechlab/interop-test-platform#261]
As a user, I want to get a reminder of what email address I used to register with (to e.g. debug why my group admin can't add me to a group). 

Tasks:

-   [ ] On the user profile page, display the email address as a non-editable field.

**Comment by jcakokorev** [comment]
Yeap, make sense. Also as alernative we can also shown on account menu both Name and email like https://prnt.sc/trp3je

**Comment by jcakokorev** [comment]
Already done by this https://github.com/gsmainclusivetechlab/interop-test-platform/pull/259
