### ISSUE TITLE
500 error after registration

### ISSUE THREAD

**Issue by agalaguz** [gsmainclusivetechlab/interop-test-platform#263]
Issue found on http://staging.interop.gsmainclusivetechlab.io/register

I see 500 error after the completed registration

## Steps to reproduce

1. Go to regsitration page
2. Fill in the registration form with all valid data and agree terms
3. Submit the form
4. See a 500 error
![image](https://user-images.githubusercontent.com/16337770/89048932-2684aa00-d359-11ea-8d80-b39fe5dbf0ff.png)

## Expected outcome

I should see a thank you message or login page

## Actual outcome

I see 500 error

**Comment by jcakokorev** [comment]
I think there is issue with mail config of mailhog. So current issue and this one https://github.com/gsmainclusivetechlab/interop-test-platform/issues/264 dependent each other

**Comment by cjol** [comment]
I didn't spot this bug report until now, but yes. The problem was that the mailhog docker service wasn't set start in the CI config for staging. So this issue should now be solved. 

Also closes #264.
