### ISSUE TITLE
Editable Testcases

### ISSUE THREAD

**Issue by cjol** [gsmainclusivetechlab/interop-test-platform#281]
As test-case creator, I want to be able to iterate on the development of my testcase by uploading new versions of the testcase yaml.

Currently iterating on test-cases is a frustrating process. Making a change to the request templates means:
1. Creating a new test-case
(1.5. Delete the old test case before you forget which one is which and select the wrong on in the session creation wizard).
2. Creating a new session to use this test-case
3. Reconfiguring component URLs to point to the new session. 

Rather than replace the test case destructively*, we need to create a new test case in the database. The new TC should be a copy of the existing TC in terms of metadata (name, description, etc). It should also have a version number, which is equal to the existing TC's version number (or 0) plus 1. Alternatively, it should contain a reference to the previous TC version. Finally, the existing TC should be archived so that it is no longer available to select for newly created sessions.

By storing the version number inside the new TC record, we can easily present a nice interface to "update" the TC included within a session. When opening a session, we can check to see if any of the test cases included have newer versions. If this is the case, we can offer a one-click "update" button to remove the outdated TC and replace it with a new one. This test-case editing functionality is already available from the work in #276.

#### *Why not simply replace the Test Case?
We could simply add an "upload yaml" button to the existing "Edit Test Case" window. This would parse the yaml and replace the contents in the database. This is a little tricky because the yaml is exploded across multiple locations in the database, and so there are potentially a lot of places to update - not all of which will be possible to do safely (e.g. what test step should we map historic test executions to?)

**Comment by cjol** [comment]
@SamyBouch Take a look at this and let me know what you think.

**Comment by agalaguz** [comment]
hi Christopher @cjol , 
I just wanted to clarify some points re Editable Test Cases tasks, this one #281 and #303.
My assumptions are based on comments in [#292](https://github.com/gsmainclusivetechlab/interop-test-platform/issues/292#issuecomment-722516859) item 5.   

So, in few words #281 is focused on versioning of Test Cases and #303 is focused on UI part of editing those version. 
(Please correct me if I'm wrong)

Based on that withing #281 we need to prepare an ability for TC creators/Admins/Superadmin to manage TC versions.
In more details, they need an ability to:
1. Import a new version of the existing TC ([example from TC list](https://prnt.sc/ve61d7))
2. Create a new version of a TC from the previous version ([example from single TC versions page](http://prntscr.com/vembne)) 
3. Delete a version
4. Edit a version (presumably via UI in #303 - may be will need something like "This is just a little change (don't save a new version)" later so every edit does not create a new version)
5. Test new version of TC prior to making them active (and available for common users), I guess admins will have some "[Version selectors](http://prntscr.com/vemecb)" on Session create/edit page. 

If items above are close to truth, seems that this question comes up:
- Once a new TC version is activated - will all common users need to somehow update their existing session with a new version or they will need just create a new sessions that will pick up the latest TC version? 

Please let me know if this makes sense and let me know your thoughs on it?
Thank you!

**Comment by cjol** [comment]
Hi Anton,

I think the version management you're talking about is more detailed than we need. What I want is a "append-only ledger". Functionally, this means that every time you "edit" a test case, instead of actually editing it, a new version of the TC is created with the change applied. So, TC creators need to be able to do the following: 

1. Edit a test case (behind the scenes, this will create a new version). For now they can just upload a new version of the YAML, but in future this editing might happen via UI in #303 .
2. View the latest version of a test case. 

For now, there is no need to delete versions - the TC creator can simply upload a new version that undoes the unwanted changes. There is also no need to display previous versions of a TC. For now, we will just display the latest version, along with the version number. (In future, we might add the ability to _view_ a historic TC, but you should never be able to change an old version).

It's also important that _every_ change to a test case results in a new version. There's no such thing as "This is just a little change" because even a little change might make a test which previously pass start failing. Once a TC version is created, it is immutable and it should be impossible to modify. The only thing a user can do is to create a new version which contains the desired changes.

Finally, creating a new TC version should _not_ automatically update existing sessions. Session owners will have to go to their session, where they will see a small notice saying "New Version Available". Clicking this notice will allow the session owner to update the TC version to the latest. See this section of the original issue:
> By storing the version number inside the new TC record, we can easily present a nice interface to "update" the TC included within a session. When opening a session, we can check to see if any of the test cases included have newer versions. If this is the case, we can offer a one-click "update" button to remove the outdated TC and replace it with a new one.

Note that the ability to update a TC version within a session should only be available in sessions where the user is allowed to edit test cases. In a compliance session, for example, the user should not be prompted to update a TC version because it is not allowed to edit test cases in a compliance session.

**Comment by agalaguz** [comment]
Hi Christopher,
Thank you for your comments, they definately make sense to us.
(Hope you understand that I didn't want to overcomplicate the platform, and just was thinking about possible helpful solutions)

**Comment by cjol** [comment]
Your thoughts and questions are definitely appreciated - it is just as helpful to discuss "overcomplications" so that we can deliberately exclude them as it is to discuss the features we do decide to implement!
