### ISSUE TITLE
Questionnaire Definition Parser

### ISSUE THREAD

**Issue by cjol** [gsmainclusivetechlab/interop-test-platform#292]
As a platform administrator, I want to specify a set of questions which users can answer to automatically select a relevant set of test-cases. The questions and mapping logic will be defined in YAML for now - in future we may expand this to include a visual interface.

This issue is to define the data structure used, and covers the import work as far as defining the questionnaire type. The work of creating the interface for users to provide answers to the questions as part of session creation is covered in #293. 

## Sample Questionnaire Definition File

  In the example below, I'm using Laravel's validation logic for preconditions. A list of preconditions is defined to be valid if all properties validate
    
    name: Sample Questionnaire
    ----
    questions:
	    section:
		    name: "Section One"
		    description: "Some section description goes here"
		    questions:
		      - property: category
		        question: What category do you want?
		        type: select
		        values:
		          first: The first one
		          second: The second one
		      - property: subcategory-first
		        question: Which subcategory of "first" do you want?
		        preconditions:
		          category: "in:first"
		        values:
		          A: Subcategory A
		          B: Subcategory B
		      - property: sync
		        question: Synchronous or Asynchronous?
		        type: multiselect
		        values:
		          sync: Synchronous
		          async: Asynchronous
    
    test_cases:
	    A-async:
          subcategory-first: "in:A"
          sync: "in:async"
	    B-async:
          subcategory-first: "in:B"
          sync: "in:async"
        B-sync:
          subcategory-first: "in:B"
          sync: "in:sync"
        second:
          category: "in:second"

## Requirements
 - Questionnaire YAML will be comprised of two sections: `questions` and `testcases`.
	 - The `questions` field is separated into multiple `sections`. The sections are used to separate logical parts of the questionnaire to improve user experience. Each section may optionally define a `preconditions` field, which behaves as for individual questions below.
	 - `questions` defines a list of questions to be presented to a user. Each question is defined by:
		 - `property` The name of a property which may be referred to in other parts of the document
		 - `preconditions` A set of validation rules which must be true in order for the question to be displayed. This allows us to have a dynamic interface, where questions which are not relevant based on previous answers are hidden from the user.
		 - `type` The type of the question. To start with, two options will be possible: `select` and `select-multiple`.
		 - Other properties will depend on the selected `type`. For both `select` and `select-multiple`, two other properties are defined:
			 - `question` A string representation of the question to show the user
			 - `values`. Key-value pairs indicating the options that a user may choose. The key is used as a logical ID for the answer, while the value is displayed to the user.
	 - `test_cases` defines a list of test cases which will be selected, depending on the users answers. This takes the form of a set of key-value pairs, where the key refers to the `slug` of a test case (see below), and the value is a set of validation rules, following the same logic as `preconditions` in the `questions` section.
 - Preconditions are used to represent arbitrary mapping logic from the user's answers to a set of test cases. They are represented as a set of key-value pairs, where the key corresponds to the `property` field of one of the other `questions` defined. The value needs to represent some kind of boolean predicate (`if X then true else false`) on the user's answer: for now, I suggest that we use Laravel validation rules for simplicity, although I am open to other suggestions too. We can expand the expressiveness of these preconditions in future development.
 - Test case data model should be augmented to add a `slug` field, which is defined in the test case YAML. Some existing test cases define a `test_case` field which is inconsistently used - it would be acceptable to use this instead of `slug`. We cannot use a test-case ID directly to refer to a test-case from a questionnaire, since this may be different from one deployment to another depending on the order of insertion of test cases. Instead, the `slug` field is enforced to be unique across all test-cases, and provides a lookup index which can be used in the questionnaire mapping logic.

**Comment by agalaguz** [comment]
hey Christopher @cjol, hope you can assist us with the next pack of questions:
1. A single quiestioonaire per system is enough? I.e. superadmin has an option to upload a Questionnaire file as YAML like a Test Case one time. The next upload will just rewrite it.
2. In case of multiple Questionnaires support, do we need to have a list of them on UI, select the active one or edit them via UI like Test Cases (#303 )
3. The type of the session (test or complience) selection can be taken on Session create button ([example](https://prnt.sc/vdyoru)) or it should be an additional step on Session creation steps ([example](https://prnt.sc/vdz1x8))?
4. What do you think if the Questionnaire to be the first form/section ([example](http://prntscr.com/vdz840)) after the Complience session selection and all the other steps to remain the same i.e. [Select SUT](http://prntscr.com/vdz5ml), [Session name and list of non-editable TestCases](http://prntscr.com/vdz6g3), and [Configuration step](http://prntscr.com/vdz6ty)?
5.  Can you please specify why we need to use `test_case` or `slug` [values](https://prnt.sc/vdz8uf) instead on `name` that are already used on Test Cases YAML for [Use Cases and Components](https://prnt.sc/vdzbis)? We guess it would be easier to find the name of the Test Case during the Questionnaire creation rather than slug that is not visible on UI.. But maybe we are missing something? 
Thanks!

**Comment by cjol** [comment]
1. One questionnaire is enough. I can imagine a future where we will want multiple, but for now let's not worry about it.
3. I'd rather have it as a separate step, because we might want to include some text to explain to the user what the different session types are.
4. That sounds fine.
5. I'm happy to use the `name` but then `name` needs to be forced to be unique among all test cases (I don't think it currently is). This will have an impact on uploading new test-cases which have the same name as an existing one (my preference would be to append a version number to the new version if there is a conflict with an existing test case), and on editing test case names.

**Comment by agalaguz** [comment]
Thank you for your comments! @cjol 
1-4 seems to be resolved.

5. Just a few thoughts on it.
Got your point re `name`. Right now all test cases from /seeds looks like unique, but, yes, in some time (especially when we have new version of MM API or Mojaloop API), a new Test Case called e.g. "Authorized Transaction by Payer FSP" may be required, so we have 2 TC with the same name, but assigned to a different Components. 
Seems like some unique field like `slug` should help with it (I guess an example of it is `authorized-transaction`) and we'll need to add an additional validation on TC YAML upload that will check if a TC with the same `slug` exists and deny duplication.
Later on once we start #281 - TC versions will be added so admins will have an option to upload a [newer version](https://prnt.sc/ve61d7) of the existing TC and on its single page admins will have an option to [select an active version](https://prnt.sc/ve63c4) of TC. This way we'll have technically many versions of a single TC, but only one will be active, so no conflict for Questionnaire. 
Please let me know if this makes sense?

6. Meantime, one more qiestion came up...
Can we change the format of adding `preconditions` from:
```
 preconditions:
	          category: "in:first"
```
to 
```
preconditions:
   category:
      - first
```
?
This will be easier for the fronted that don't work with "in:first" format to generate next steps on fly.

Thanks!

**Comment by cjol** [comment]
5 and 6 both look fine to me!

**Comment by cjol** [comment]
Actually, thinking a little harder about 6:

For now, I think all validations will be of the form `in:X` but in the future we might like something more powerful (like `gt:Z`). To futureproof ourselves, I would prefer this format:
```
preconditions:
   category:
      - in: first
```

For the purposes of this task, I am happy for the frontend code to assume that all entries are of the form `in: `. Does that make sense?

**Comment by KolyaSirik** [comment]
Hi, Christopher @cjol 

I think, this is a good format for us:
```
preconditions:
   category:
      in: first
```
