### ISSUE TITLE
Email Invitations

### ISSUE THREAD

**Issue by cjol** [gsmainclusivetechlab/interop-test-platform#294]
As a group administrator, I want to easily invite new users to join the platform.
Currently, the flow to do this is that the new user needs to manually create an account, and then the group admin can lookup the user's email address to add them to the group.

Instead of this, the "Add User" flow should be augmented. Currently, a dropdown list is shown of users whose email address match the group's domain filter. It now should be possible to enter any email address (which matches the domain filter) even if that address is not registered to the platform.

 - if the email address corresponds to an existing user, that user should be shown in the autocomplete window, and would be added to the group immediately (unchanged behaviour)
 - If the email address does not correspond to an existing user, the admin will be shown a prompt, asking if he would like to send an email invitation to the user. 
 - If the admin approves, an email will be sent to the new user, containing a registration link with a unique invitation code.
 - A field for entering the invitation code should be displayed in the registration form, but it should be prefilled from the emailed link. In case the field has not been prefilled (e.g. the user is registering on a different device), the user can enter the value manually.
 - After filling in the registration form, the invitation code is used to automatically assign the user to the user group. The invitation code should also be invalidated to prevent reuse.
 - When a user registers with an invitation code, the "Email verification" step is skipped, and the user should be logged in immediately after filling in the registration form.
 - The invitation feature must be available to group admins, but should also be accessible to platform admins, who may use this feature to bootstrap a new group by inviting the first users (see #295)

**Comment by agalaguz** [comment]
@jc-skushnir some notes about this task and some of the related ones (#295 and #296):
1. The invitation code
   - is unique per invitation i.e. every user will receive own uniqe code
   - should be a 6 characters value (for now it is enough, later on we may difits or other sybols and extend its length)
   - should have an expiration time (can be set via config file)
   - should be used by only one person, i.e. can't be 2 registration using a single code
2. Once invited user used the invitation link and was redirected to the Registration page
3. The list of invited users should be visible for Group admin and Platfrom admin
4. Group admin and Platfrom admin can remove inviations and re-send them

**Comment by cjol** [comment]
Some notes copied from our conversation: 

> 1. If the user is entering the code manually from a different device, we can't block them from entering a different email address. In this case I think it should trigger a validation error if the email address they enter is different from the one that the invitation code is associated with.
> 2. We do need to be a bit careful about security, because we are not only allowing registration but also granting access to an existing user group. To combat this, my preferred solution would be to add rate-limiting to one registration attempt per second for a given email address. This could be combined with a short code (6 Uppercase + Numeric chars) that is easy to enter but would still take several years to crack. I don't know how easy this is to achieve in Laravel, however, and I don't want to increase the scope of the ticket. So if it's not easy to do rate limiting, I would rather stick to a long code (15 Upper, Lower + numeric characters)
