### ISSUE TITLE
mTLS for incoming requests

### ISSUE THREAD

**Issue by cjol** [gsmainclusivetechlab/interop-test-platform#298]
As a platform user, I want to be able to send encrypted messages (as if I was interacting with a real environment), and have the messages decrypted and validated before passing them on.

## Requirements
- When an incoming request arrives using an encrypted TLS connection, it should be decrypted in order to allow PHP to receive the message and process it.
- The response to the request from PHP should be encrypted and sent onwards to the client. 
- Only the `/sut` endpoints should be encrypted in this way
- nginx should still allow unencrypted (HTTP) connections in addition to the encryped connections above
- I want to be able to add a "Was encrypted?" conditions to certain test cases, so that we may have both "Encrypted" and "Uncrypted" versions of a test case (which will be selected by the user during the questionnaire). I would suggest configuring nginx to add a custom header to the incoming request to indicate whether HTTPS was used (e.g. `ITP_MTLS_ENABLED=1`). In future, we could hide this header from the test case page so that users don't get confused about where it came from.

## Discussion

mTLS is a [Network Layer](https://en.wikipedia.org/wiki/OSI_model#Layer_3:_Network_Layer) protocol, so by the time the request reaches PHP (Application Layer) it's already too late. Instead, we need to decrypt with mTLS within the nginx proxy. The response from PHP will also pass through nginx and will need to be encrypted.  The basic idea (as I understand it) is:

- We set up a Certificate Authority (CA) certificate and key
- We create a Server certificate and key, and sign the Server certificate with the CA. 
- We share our CA certificate with clients (i.e. with Mojaloop hub and DFSPs) so that they know to trust our Server certificate. [1]
- We configure nginx to use the Server certificate and key (`ssl_certificate`/`ssl_certificate_key`) to encrypt responses
- We fetch CA certificates from our clients (i.e. Mojaloop hub and DFSPs) so that we know to trust their requests. [2]
- We append all client CA certificates into one file, and configure nginx to use it to verify incoming requests (`ssl_client_certificate`).

This is a fairly common scenario to implement, and there are many resources explaining how to do so (see below) - often under the term "Client Certificate Verification". The nuance is in distributing certificates ([1] and [2] above). 

### Distribution
[1]. Our CA certificate should not change very often. We can share it manually with the Mojaloop hub (via MCM for Mowali). For DFSPs, I think it's okay simply to publish our certificate in a new page on the platform. 
[2]. Mojaloop CA certificate will be again be unchanging, but we still need a system for DFSP certificates to be shared with us. I can think of three options:
  ~(a). DFSPs upload their certificates to Modusbox Connection Manager (MCM), and ITP fetches them automatically. This is a smooth experience for the DFSP because it mirrors the "normal" onboarding process, but it would require us to have "hub" access to the MCM api.~ (this requires too much work)
  (b). DFSPs upload the certificates into the platform somewhere. This probably makes most sense at the group level.
  (c). Platform admins collect the certificate from externally (E.g.  MCM) and uploades them into the platform somewhere. 

Both options b and c can be combined to allow either platform admins or DFSPs to upload certificates themselves, depending on the preferred workflow for the environment. 

## References
I've followed a mixture of web blog posts and other resources to achieve the understanding above, and I am including the links below as much for my own understanding as anything else.

- [Blog Post on setting up mTLS with nginx and a Postman client](https://dev.to/darshitpp/how-to-implement-two-way-ssl-with-nginx-2g39)
- [Stackoverflow answer on using multiple client CAs](https://serverfault.com/questions/412432/how-to-specify-multiple-root-certificates-for-nginx-client-certificate-verificat/653879)
- [Slightly more details blog post on mTLS](https://jason.whitehorn.us/blog/2019/02/01/client-certificate-auth-with-nginx/)
- Modusbox Connection Manager User Guide (pdf from Mowali)
- [Modusbox Connection Manager API repository](https://github.com/modusbox/connection-manager-api) (in particular the swagger file describes all relevant endpoints)
- [Mojaloop encryption documentation](https://docs.mojaloop.io/mojaloop-specification/documents/Encryption.html)

**Comment by KolyaSirik** [comment]
Hi Christopher, @cjol 

Just one question. We don't have ability to receive HTTP and mTLS requests in one endpoint.

Is it okay if we will add `/testing-mtls/*/sut` for mTLS and keep `/testing/*/sut` for HTTP ?

**Comment by cjol** [comment]
Yes, that's acceptable - however I would prefer these URLs:

`/testing/*/sut` for mTLS
`/testing-insecure/*/sut` for HTTP
