### ISSUE TITLE
Allow 0-N SUTs

### ISSUE THREAD

**Issue by cjol** [gsmainclusivetechlab/interop-test-platform#310]
Currently, we use a "real" Mojaloop instance instead of a simulator, because it gives us greater confidence that our implementation is realistic. By doing this, we are not susceptible to simulator bugs.

This can also be the case for other components. From our conversations with platform operators, it has become clear that DFSPs sometimes want to test an integration with a specific other (real) DFSP. Although functionally this _should_ be the same as running two tests with a single SUT, in practice more confidence is desired that the results are "real".

This creates a motivation to allow N SUTs for N>1. However, I can also think of two usecases where having 0 SUTs is desirable:
1. When developing a test case, we may not have a real implementation to test. Allowing 0 SUTs would allow use of a simulator for all components. This would also have the benefit of simplified connectivity - no need to set up a local tunnel to test a local component.
2. When learning about ITP or about a flow in general, it is useful to be able to run a test without a SUT. Currently, we sort of allow this with a mixture of Postman and a hosted server to receive callbacks (https://beeceptor.com/), but it's a bit clunky, and it only works for SUT-initiated requests. By supporting 0 SUTs, we can create a session that is instantly runnable with no external tools - every request will be simulated, and obviously there will be 0 failures.

Note that the 0 SUT use case is much more powerful if combined with #309 because we can then support any possible flow of HTTP requests using only the test case definition, with no dependency that the logic has been implemented inside a simulator.

In theory, this shouldn't be too big a change in terms of test execution. As mentioned above, we currently run a "real" Mojaloop, so effectively we are already running 2 SUTs. The big changes (I think) will be in adapting the user interface around session creation, to provide the configuration URLs for various external SUTs.

**Comment by brunosmm** [comment]
Maybe we can link in a way you are able to customize the URL for the components. Today a component has a fixed URL and the SUT works removing this component and adding the external one.
If we are able to create possible flow combinations like: SUT -> Moja -> Sim / SUT -> SUT -> Sim / etc, that would lead the UI to have this extra fields to setup the url for each SUT in the flow...

**Comment by agalaguz** [comment]
Hi Christopher, @cjol 
Could you please have a look at [these wireframes](https://drive.google.com/file/d/1rGZ7qD9kvTQmItua0ebJnD1cJjdN8M2y/view?usp=sharing) fot the SUT selection step?
Seem like this is the only step where UI will be affected. The other point is any TC step will show more Configuration links, e.g. if I selected MMO1 and MMO2 as SUTs -> the [configuratoin URLs](http://prntscr.com/vk4u0g) for both willbe shown.
Hope this makes sense.

**Comment by cjol** [comment]
I think this is functional, but the interface is a little overwhelming. The primary use-case will still be with one SUT, so displaying four dropdowns is a little much. 

What do you think about adding a checkbox underneath each component in the connection diagram, labelled "Test Component". When the user ticks the box, the URL configuration fields will appear beneath, as in your wireframe. In the default case, no components are selected for testing, which means they will all be simulated.

Currently you are right about the Mojaloop setup, because our Mojaloop installation is being used as a glorified simulator. However once we work on #309 , selecting "Simulator" should bypass Mojaloop completely and just use the test case definition. To replicate the current setup, the user will need to select "Test Component" and enter our Mojaloop url. This is a little bit awkward, but it's tolerable for now - a future issue might tighten up this experience by prefilling the Mojaloop URL field with ours.

On the TC page, things look fine. It's starting to get a little crowded in that sidebar, but it's again fine for now. A future issue might look at redesigning this page to give this information a little more space to breathe!

**Comment by agalaguz** [comment]
Hi Christopher, @cjol 
Thank you for your comments.
In regards to session creation steps, could you please have a look at a [new mockup](https://drive.google.com/file/d/1fltFs3ROxzhFNxkvi_cQttC2Oj-MW8Xx/view?usp=sharing)?

**Comment by cjol** [comment]
Hi Anton, that looks good now. I prefer v3 with the switches.

**Comment by cjol** [comment]
Here is an example of some different use cases for 0-N SUTs:
![Screenshot 2020-11-19 at 15 09 10](https://user-images.githubusercontent.com/1517675/99685270-4e1f8f80-2a7a-11eb-8523-662793efce69.png)

**Comment by agalaguz** [comment]
Hi Christopher @cjol, 
Just wanted to confirm how the number of SUTs aligned with available Test Cases on Session (selected during [Session creation screens](http://prntscr.com/vtoad9)).

So, for example, if 

- **0 SUTs** selected -> all TCes can be selected
- **1 SUT** selected -> TCes where [this Component has mentioned](http://prntscr.com/vtocf5) are available.
- **2 or more SUTs** selected -> TCes where all these SUTs were mentioned are available. _E.g. I selected SP, MMO1 and MMO2 as SUTS -> this means that Merchant Payment is available as includes these 3 components. P2P is not available as it includes only 2 of 3 components._

or, in opposition, show all TC where at least 1 of selected SUTs is mentioned.  

Could you please let us know what is better?

**Comment by cjol** [comment]
Hi Anton, good point. Let's go with the _more_ permissive approach for now which should be less annoying if that turns out to be the wrong decision. Show all test cases where at least 1 SUT is mentioned (or all cases if 0 SUTs are selected).

**Comment by agalaguz** [comment]
Hi Christopher @cjol,
Just wanted to ask if we are to make any specific restrictions for Compliance sessions. 

e.g. 

- `Test` and `Test + Questionnaire` sessions may have **0-N** SUTs (no restrictions)
- `Compliance` session seems to have **>=1** SUTs or a **single** SUT?

**Comment by cjol** [comment]
Another good question. 0 SUT doesn't make sense for Compliance sessions, so let's exclude that. The most common mode for compliance will be 2 SUT as we have now (1 DFSP + Mojaloop). Let's allow >= 1 SUT for Compliance. 

In future we might want to let admins restrict this further on a platform-by-platform basis but I'm not sure what the best interface for that would be yet, so I'm happy to leave it open for now.

**Comment by cjol** [comment]
I think we will add a concept of "compliance configuration" in future. This will provide a visual interface for admins to control:
 - Whether to enable test mode, compliance mode, or test+questionnaire modes
 - Questionnaire Management
 - Which SUTs can be selected for Compliance
 - ... Other

I don't want to invest much time into this "Compliance Configuration" screen yet because I want to get feedback from our users first, to figure out what it is that they feel that they want more control over. Then we can design the feature more thoughtfully.
