### ISSUE TITLE
PHP Fatal error when generating test reports

### ISSUE THREAD

**Issue by cjol** [gsmainclusivetechlab/interop-test-platform#320]
High-level summary of the problem.

## Steps to reproduce

1. Build the latest docker images
2. Run `yarn test` to execute tests

## Expected outcome

Tests pass, and report files are generated successfully.

## Actual outcome

Tests pass, but report fails to generate, throwing the following error instead:
```
Generating code coverage report in Clover XML format ... 
[PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:1038
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(839): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(712): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array, true)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Foundation\Application->resolve('Illuminate\\Cont...', Array)
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\Container\Container->make('Illuminate\\Cont...', A in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 1038]
[PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:1038
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(839): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(712): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array, true)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Foundation\Application->resolve('Illuminate\\Cont...', Array)
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\Container\Container->make('Illuminate\\Cont...', A in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 1038]
```

Full log should be accessible here: https://app.circleci.com/pipelines/github/gsmainclusivetechlab/interop-test-platform/956/workflows/1bc669d5-53ea-40b2-93fa-ec1ab1e65ac0/jobs/631

Current theories:
 - Something to do with composer updating to 2 (the [last successful develop build](https://app.circleci.com/pipelines/github/gsmainclusivetechlab/interop-test-platform/911/workflows/b8141de4-ae3f-4787-96be-ab02272caf09/jobs/623/parallel-runs/0) was still using composer 1). I'm not sure though, because I checked out develop locally and rebuilt it (which fetched composer 2 automatically, and which required me to remove prestissimo). That build succeeded and test reports successfully generated, so it doesn't seem to be that.
 - Something to do with file permissions inside the docker container. The latest comment on [this issue](https://github.com/laravel/framework/issues/28809) suggests this can be a cause, and it's not at all unlikely that's the case here. To debug, we'll probably need to step inside the container and gradually add file permissions until we figure out which files are required.

**Comment by cjol** [comment]
I've added a workaround to allow CI to complete in https://github.com/gsmainclusivetechlab/interop-test-platform/commit/81cba4db605b39c79991bfbbd4371cc0a700d831, which I'm about to merge into master. Once this issue is fixed, that workaround should be reverted.

**Comment by KolyaSirik** [comment]
I've updated composer container in Dockerfile to 2nd version. We can try with this.
I can't reproduce it locally and on staging
