### ISSUE TITLE
Compliance session export file -> add more info

### ISSUE THREAD

**Issue by agalaguz** [gsmainclusivetechlab/interop-test-platform#327]
The compliance session contains some useful info that can be added to the [export file](http://prntscr.com/vsr6fd).

Some ideas re info below.

### Compliance session summary

**Info**
Session name: {`Session #1 name`}
Session description: {`This is a comprehensive description of my session`}
SUT: {`Service Provider`}
SUT URL: {`http://gsma-sp.staging.s8.justcoded.com`}

**Events**
Creation: {`2020-11-27 12:05:06`}
Completion: {`2020-11-28 12:05:06`}
Approval/Decline: {`2020-11-29 12:05:06`}
  
**Questionnaire**
{`Section 1 e.g. Merchant payment section`}
Q1: {`Does your engine support Merchant-Initiated Merchant Payment?`}
A1: {`Yes, it does`}
Q2: {`What Test Case behaviors are you interested in?`}
A2: {`Positive`}
{`Section 2, e.g. P2P transfer section`}
Q1: {`Does your engine support P2P Transfer?`}
A1: {`No, it doesn't`}

**Test Runs** ([like they are now](http://prntscr.com/vsrnac))

**Comment by agalaguz** [comment]
Hi Christopher @cjol, 
I added some ideas re how to add a bit more info to the Compliance Session export file template (based on our demo meeting chat). Could you please take a look at let me know if this works?

**Comment by cjol** [comment]
Thanks Anton, this is good. The most important one is the questionnaire answers. Other fields that might be interesting:
- Group name
- Environment values and variables
