### ISSUE TITLE
Control Available Session Modes

### ISSUE THREAD

**Issue by cjol** [gsmainclusivetechlab/interop-test-platform#330]
There are now three session-creation modes: Test, Compliance, Test + Questionnaire.

Not all installations of ITP should have every mode available. I would like three environment variables created in 

When a mode is disabled, the button to select it should not be shown (nor should the corresponding explainer text). If there is only one mode enabled, the screen should be skipped, and the user starts with the next step instead.

**Comment by agalaguz** [comment]
@cjol if 3 environment variables are set to `false`, we'll need to handle it somehow, e.g.
- Show some warning/error during the platform setup that forces user to set at least one variable to `true`
- Disable the "create session" button once the platform is setup and show some message why it is disabled

Could you please advise?

**Comment by cjol** [comment]
Good point. Let's show a big banner on the homepage saying "No test modes are enabled in the environment".
