### ISSUE TITLE
Allow variable numbers of requests in a test case

### ISSUE THREAD

**Issue by cjol** [gsmainclusivetechlab/interop-test-platform#335]
As alluded to in #334, we want to be able to support polling-based APIs. Right now, all test cases have a fixed number of expected requests, but this is problematic for polling. With polling, we don't know if the resource will be ready after 1 poll or after 5, so we can't anticipate how many requests will be required to "pass" the test case.

Solution outlined here: https://github.com/gsmainclusivetechlab/interop-test-platform/issues/335#issuecomment-762402848

**Comment by brunosmm** [comment]
Just raising an idea...
Maybe add a value of maximum time to wait on this step and get a positive result, within this time can receive may requests/response, and after this time the test case evaluates the result based on the last message.
The pooling interval is defined by the server so this information would be best processed by the response, not sure how to handle this? Is a response having a possibility to change environment variables?

**Comment by cjol** [comment]
I don't love the idea of allowing responses to change environment variables yet. I can imagine it might be necessary one day but I am keen to delay as long as possible! In this case I would say that the polling interval is probably pretty static for any given server. So whoever sets up the test session can set the polling interval once in the environment and we won't have problems. 

For clarity: I'm specifically worried about the case where the SUT is providing the resource and ITP are polling it. In the case where a client is polling ITP, it's quite easy: just have a fixed 1 response saying "not ready" and then a fixed 1 response saying "here it is". No dynamic data required!

The problem with a max wait time is if we just blindly poll during the window, we might have multiple successes (and that might not be allowed by the API spec). A better solution might be to have an optional `repeats` parameter on a test step. The simulator will repeat the request until the response does not match the expected one, at which point it will try to match the next step's response instead. 

That's not a full solution because now we've got a situation where a request from one step is associated with the response for the next step. Maybe we can define two `response` fields for a step:
1. A "repeat" response. When the ITP receives a response matching this, it validates it and then repeats the previous request.
2. A "terminate" response. When the ITP receives a response matching this, it validates it and the moves on to the next step.

We'll need to be a bit thoughtful about how we want to record it (i.e. if the request is repeated three times, do we show all three on the test results? Probably.). And even more thoughtful about how we "count" the steps for the purposes of later variables like `${test_steps[3].response.body.myFooValue}` (maybe we don't count "repeat" responses at all, so `myFooValue` would have been read from the "terminate" response in that example?)

**Comment by cjol** [comment]
Here is my proposed syntax for supporting repeating test steps as necessary for polling-based APIs. Note the new (optional) field at `step.repeat`:

```yaml
 - path: /get-status
    pattern: '^get-status$'
    method: GET
    source: source-component
    target: target-component
    test_response_scripts:
      - name: Transaction was successfully accepted
        rules:
          body.result: 'SUCCESS'
          status: 'required|in:200'
    request:
      method: GET
      uri: /get-status
    response:
      status: 200
      body:
         result: 'SUCCESS'
    repeat:
      condition:
        body:
           result: 'PENDING'
      max: 3
      count: 2
      response:
        status: 202
        body:
           updatedTime: '{{ "now" | date }}'
           result: 'PENDING'
      test_response_scripts:
        - name: Request was received
          rules:
            body.result: 'PENDING'
            status: 'required|in:202'
```

- `repeat.condition`: If a SUT response matches `repeat.condition` then the test run does not proceed to the next step and we will continue by listening for the same request again. "Matching" can be implemented like we presently do for `step.trigger`. The request and response do not need to be accessible from twig for now, so the `step.N.request` variables should not be modified and the current step number is not incremented.
  - If a SUT sends a response which does _not_ match `repeat.condition`, the test run will proceed as normal (so the response will be checked using `step.test_response_scripts`, and the current step number is incremented).
- `repeat.test_response_scripts`: These tests should be used instead of `step.test_response_scripts` when the response matches `repeat.condition`. The test results should be appended to the main test step (i.e. we don't add any extra "steps" to the final test report, but there will be some additional tests under the step which has been repeated). 
- `repeat.max`: If the response sent by a SUT matches `repeat.condition` more than `repeat.max` times, the test fails.
- `repeat.response` and `repeat.count`: If the response is generated by a simulator, it will use this "repeated" response instead of the normal `step.response` to start with. `repeat.response` should be used `repeat.count` times, after which a final response should be generated using `step.response`.

To demonstrate that the approach above satisfies our requirements, there are four cases to consider:
### `source-component` is SUT, `target-component` is SUT
We don't control any behaviour. The request from `source-component` is validated as normal. The response from `target-component` is first compared against `step.repeat.condition`. If it matches, `step.repeat.test_response_scripts` is used to validate it, and the step is repeated. If it does not match, `step.test_response_scripts` is used to validate as normal and the test case proceeds.

### `source-component` is SUT, `target-component` is simulator.
We control the _response_ behaviour. The request from `source-component` is validated as normal. As a simulator, we check whether the current step has been repeated less than `step.repeat.count` times. Because it has, we generate a response using `step.repeat.response` and validate it using `step.repeat.test_response_scripts`. The test case does not move on to the next step, instead awaiting another request from `source-component` to the same URL. The process repeats `step.repeat.count` times, after which the simulator generates a final response using `step.response`, which is validated by `step.test_response_scripts` as normal and the test case proceeds.

### `source-component` is simulator, `target-component` is SUT.
We control the _request_ behaviour. As a simulator, we generate a request using `step.request` as normal. The response from `target-component` is first compared against `step.repeat.condition`. If it matches, `step.repeat.test_response_scripts` is used to validate it, and the step is repeated as we generate another request using `step.request`. When we receive a request which does does not match `step.repeat.condition`, we validate it using `step.test_response_scripts` as normal and the test case proceeds.

### `source-component` is simulator, `target-component` is simulator.
We control the _request_ and _response_ behaviour. As a simulator, we generate a request using `step.request` as normal. 
As a simulator, we check whether the current step has been repeated less than `step.repeat.count` times. Because it has, we generate a response using `step.repeat.response` and validate it using `step.repeat.test_response_scripts`. The test case does not move on to the next step, and so we generate another request using `step.request`. The process repeats `step.repeat.count` times, after which the simulator generates a final response using `step.response`, which is validated by `step.test_response_scripts` as normal and the test case proceeds.

Reminder, we will be adding delays with https://github.com/gsmainclusivetechlab/interop-test-platform/issues/334

**Comment by jc-skushnir** [comment]
Hi, @cjol 
i've got some questions about this task:
- `repeat.condition` and `repeat.test_response_scripts` - do we need those additional fields? Can't we just do a check for `test_response_scripts` and if we don't pass the check, then do a repeat request?
- As I understand, we do not show the results of the repeated requests, but only the final result (e.g. body with status "seccess" or "pending" depending on the latest response). So we rewrite test result every time when match test step. Or do we need to keep somehow all repeat requests with their own response and show them on test results pages, e.g as tabs.

Thoughts: posibly test step with path '/get-status'  won`t be unique, so it would be imposible to match if it as first step

**Comment by cjol** [comment]
Thanks for asking! I think there are three possible cases when the message receiver is a SUT:
1. "success"-type message like `{"status": "SUCCESS"}`
2. "please retry"-type message like `{"status": "PENDING"}`
3. "error"-type message like `{"status": "Failure"}`

We only want to repeat the request in the 2nd case, which is why I think we need `repeat.condition` to identify those patterns. I think we also need `repeat.test_response_scripts` because we may want to validate the payloads in case 1 and 2 using different tests. For example in the demo I wrote, I want to check that the HTTP status code is `202` in the repeat case, but in the final case it should be `200`. In both cases, if the SUT sends e.g. status code `300` then the response tests will fail and the test case should be concluded as a failure.

In the end, we only need to show the final result as you describe it. Ideally, I would love to keep track of all the "assertions" that were calculated on the retried responses (like the "Intermediate Response" in the mockup below), but if this is complicated then it's fine just to discard the results. Note that if the "intermediate response" tests fail, then the test case should fail immediately and we don't need to record any further results.
![image](https://user-images.githubusercontent.com/1517675/105181284-83506880-5b23-11eb-99ac-f547c7c95b9c.png)

You're right that we would have problems if we used `/get-status` on more than one test case, but hopefully it's a nice simple example for our current conversation!

Please let me know if I can clarify anything else!

**Comment by agalaguz** [comment]
Hi Christopher @cjol,

We were thinking how better to store/show all iterations of repeat steps and feel and we need a piece of advice from you.
As an example of TC I will use the one that added [above](https://github.com/gsmainclusivetechlab/interop-test-platform/issues/335#issuecomment-762402848), where we have
- source-component (SUT)
- target-component (simulation)
- `repeat.count: 2`

So, SUT will send `/get-status` `request` 3 times and get next `responses`
1. repeat (PENDING) 
2. repeat (PENDING) 
3. final (SUCCESS) 

In fact, we have a single Test Step that includes 3 `request`-`response` sets.
So, as after the 1st request-response set we don't know if 2d and 3rd ones will be performed by the SUT, and need to run test scripts (**assertions**) that is the usual behavior. 
This leads to the next picture:   
![image](https://user-images.githubusercontent.com/16337770/107020674-d412c300-67ab-11eb-8d0e-47c4993478ad.png)
and, in addition to it, seems like set of 3 requests-responses may be needed there 
![image](https://user-images.githubusercontent.com/16337770/107022991-b2670b00-67ae-11eb-847e-e43f6f8e2603.png).

We are thinking about the next options: 
- add "tabs" per attempt within a Test Step to see all **assertions** and `request`-`response` messages
- show/store only the latest  `request`-`response` messages and the related assertions
- show/store only the latest  `request`-`response` messages but show all assertions for all attempts (maybe using some tabs)

Could you please advise? Thanks.

**Comment by cjol** [comment]
If you can find a way to display the request/responses and assertions inside tabs, then that would be great! However I was worried that would be too complicated, and if that's the case then it's fine to discard the intermediate request/responses. My order of preference (1 is most preferred, 3 is least preferred):

1. add "tabs" per attempt within a Test Step to see all assertions and request-response messages
2. show/store only the latest request-response messages but show all assertions for all attempts (maybe using some tabs)
3. show/store only the latest request-response messages and the related assertions

(And I will not be disappointed if we can only manage 3!)

**Comment by agalaguz** [comment]
Hi @cjol! we are working on option 1, and thinking how exactly tabs can be implemented from the UI perspective.
It depends on the expected max number of `repeat.count`. 
"Tabs" would look better if this number is less than 10. 
In case some test steps require more than 10 repeats - "tabs", probably, to be replaced with some "list-view" or something similar.

Could you please advise?

**Comment by cjol** [comment]
I don't expect that we will have more than 10 repeats in "normal" use, so tabs is probably fine.

**Comment by brunosmm** [comment]
Hi @jc-skushnir / @agalaguz / @cjol , 

I didn't manage to make polling work, can you check if there is some error on my TC?

Test Case: https://github.com/gsmainclusivetechlab/interop-test-platform/blob/5a952dc7eb3f4a74218c0b5e7986a45190ca36f5/src/database/seeders/test-cases/mmapi/Merchant%20Payment%20-%20Request%20Payee/Request%20Payee-Initiated%20Merchant%20Payment%20(debitParty%20and%20creditParty%20sent)%20with%20Polling%20%E2%80%93%20Success.yml

Execution: https://compliance.mobilemoneyapi.io/sessions/6/test-cases/203/test-runs/216/2 

![image](https://user-images.githubusercontent.com/1554850/108116541-7e2afe80-707a-11eb-9be5-34470e88a7be.png)

Message log: only has 1 request... so it seems the platform didn't make the second one:
![image](https://user-images.githubusercontent.com/1554850/108116658-aca8d980-707a-11eb-8c0a-b790a9a51bc3.png)

**Comment by cjol** [comment]
I might be wrong, but I think the _condition_ field is an "exit" condition for the repeat block. So in your case the simulator is sending a pending response, which matches the condition and there is no need for any repeats. 

In this case though I would have not expected any "Intermediate Response" tests to be executed, and Step 3 should be executed, so I'm not totally sure...

**Comment by cjol** [comment]
It's possibly related to the bug fixed in https://github.com/gsmainclusivetechlab/interop-test-platform/pull/456 so we should try again once I've merged it.

**Comment by agalaguz** [comment]
Hi @brunosmm @cjol,

Thank you for your comments. 
We've checked your test case and found out why it had been failed.
The test case failed because the "repeat/intermediate" step, that was successfully matched by the platform, contained a failed assertion (in your example it was MM API Response test). 
So, the test case will work fine if you add `headers` to `repeat.response`
![image](https://user-images.githubusercontent.com/16337770/108185571-1f669300-7115-11eb-8f6c-27f9808f0d0d.png)

This way we also wanted to partially cover this requirement:

> For example in the demo I wrote, I want to check that the HTTP status code is `202` in the repeat case, but in the final case it should be `200`. In both cases, if the SUT sends e.g. status code `300` then the response tests will fail and the test case should be concluded as a failure.

Thus, if any assertion inside the polling step is failed -> test case is failed. 
Now it looks for me that this condition is a quite strict, and we, rather, had to write a Test Fail condition that fails the whole test case run if any assertion in a Test Step that includes polling conditions is failed. Or, maybe, this logic should be applied to all test steps, even those that do not include polling conditions -> i.e. -> fail a test case if any assertion is failed? Could you please advise?

--

In #456 we fixed the other known issue, that was mentioned during our demo meeting last Friday -> multiple matching of polling requests from SUT that prolonged test step execution even if all conditions were matched.
