### ISSUE TITLE
iLP generation and validation

### ISSUE THREAD

**Issue by brunosmm** [gsmainclusivetechlab/interop-test-platform#342]
Current the platofrm uses fixed ilp values which is working since most of times is simulators against simulators, altough once adding a real DFPS the ilp need to be proper generate by the simulators and validate in the messages that arrived in the platform.

Tasks:

-   [ ] Validate all request/response that arrive in the platform and have the ilp value, see moja docs for more detail (Quotes and transfers)
-   [ ] Generate ilp for all requests/response generated by DFSP simulators;

Requirements:

https://docs.mojaloop.io/mojaloop-specification/documents/API%20Definition%20v1.0.html#4-interledger-protocol
https://docs.mojaloop.io/mojaloop-specification/documents/API%20Definition%20v1.0.html#listing-12

Open Points:

Requires further investigation in how to implement it.
Example of implementation from ttk: https://github.com/mojaloop/ml-testing-toolkit/blob/cbeff4a296c21f7fb0995526846a9fd8989b82be/src/lib/mocking/middleware-functions/ilpModel.js

**Comment by cjol** [comment]
As an implementation note, I think the best way to tackle this is to add a custom laravel validator function for checking incoming packets, and also a custom twig function so that we can generate outgoing packets in any context.

**Comment by cjol** [comment]
The javascript implementation is available here: https://github.com/mojaloop/sdk-standard-components/blob/master/src/lib/ilp/index.js

**Comment by cjol** [comment]
I've put together a demo PHP implementation which can be probably copied: https://gist.github.com/cjol/bef1d655a6b2d5ce2a57a243d4e06904
