### ISSUE TITLE
Sprint 12 feedback

### ISSUE THREAD

**Issue by agalaguz** [gsmainclusivetechlab/interop-test-platform#350]
Here are some notes from the Sprint 12 demo (11/12/2020):

1. **Edit Test Step #303**: good to have the ability to [paste JSON to editors](http://prntscr.com/w395fh) instead of only adding values manually.
2. **Remove simulators #309**: if we leave any `response`/`request` value (as per #303) [empty](https://prnt.sc/w397z0), will the platform generate it as an empty array as per the [screenshot](http://prntscr.com/w39ase)? Assume it should not include any empty array.
3. **Edit Test Step #303**: remove [Example word](http://prntscr.com/w39cf1) from `requests` and `responses`.
4. **TC variables #343**: show TC variables as values on [request and response](http://prntscr.com/w39gd0) in session. 
Here to specify how better to handle it:
   - maybe some variables like '**generate time now**' to be displayed,
   - but values like '**this is variable that is to be set on session env.**' to be shown like they are, 
   - and values like "**take it from `step.1.request.body.amount.amount`**" to be shown like they are or to add the ability to set some 'default values'
5. **Compliance session #244**: add the ability to set more than 1 SUT (like we do for Test session) as customers may require using some own 'simulators' and 'mojaloops'
6. **DSFP onboarding TC #310**: if the user selects Mojaloop as SUT, he needs to have the ability to setup all necessary callbacks for both DFSPs (MMO1 and MMO2) in that external Moja. Suggested to write a TC that will make all necessary queries to Moja and create 'participants' and 'session callbacks' there so that the test cases to be executed successfully.

**Comment by agalaguz** [comment]
Hi Christopher, @cjol 
I've added the past sprint feedback here.
Could you please have a look and let me know if these items make sense and we can add them to the current/upcoming sprints?
Thanks.

**Comment by cjol** [comment]
2. Note that we need the ability to return both "`[]`" (an empty array) and "` `" (an empty body). Technically "` `" is not a valid JSON document, but it is commonly used as a response payload so we do need to be able to handle it. My original suggestion was that `body` should not be modelled as a JSON document but just as a string - then we could use whatever value we wanted without being constrained by what constitutes a valid JSON document (this is also relevant for variables, which may not always be used inside a JSON string). 

.5. Let's track that one separately on #352.

Other issues I have found in my testing so far:
 - Test Steps aren't counted properly on test versions page (#351).
 - Components still have a "Base URL" field shown to admins, but I think it's not used anymore so we should hide it.

**Comment by cjol** [comment]
Related to 1 and 2, I think there are some possible fundamental issues with the way we have chosen to represent request/response templates. I have created a separate issue to discuss in #353
