### ISSUE TITLE
Group Default Session 

### ISSUE THREAD

**Issue by cjol** [gsmainclusivetechlab/interop-test-platform#382]
Users are encountering a challenge with configuring their SUTs, because the configuration settings are sometimes not easily accessible. This makes it difficult for them to change the component URLs every time they create a new session.

As a workaround for this, I would like to provide a static URL for each component, which we will internally map to the correct session. Essentially, we will transform this URL structure:
```
./testing/{session:uuid}/{componentId}/{connectionId}/sut/{path?}
```
to this:
```
./testing/group/{group}/{componentId}/{connectionId}/sut/{path?}
```

Within the user interface, a group admin can select one "default" session:
![image](https://user-images.githubusercontent.com/1517675/103801246-5ee58e00-5045-11eb-985c-ca977df08120.png)

Whenever a request comes in to the `/testing/group/...` URL, the default session for the group is queried, and the session used to resolve the request. If no default session is configured for the group, the request should be logged in the global message log, and an error returned to the client saying:
> No default session has been configured for the specified group.

During session creation, a new prompt should be added: 
![image](https://user-images.githubusercontent.com/1517675/103801880-3e6a0380-5046-11eb-9aba-6ea5f9d0d5b0.png)

- If the current user is a member of multiple groups, a tickbox should be shown for each group they are a member of
- If the current user is not a group admin, the tickbox should still be visible, but it should be disabled and not selectable. 
- When the tickbox is selected, the URLs displayed below should change to use the `/group/{id}/...` structure.

Selecting "Make Default Session" (which should be deselected for all groups by default) will set the session to be the default session for that group when the wizard is completed. Underneath the tickboxes, the following explanatory text should be included:
> Setting this as a group's default session will allow your components to keep using the same URLs. However the session which is currently configured as the default session will stop receiving any traffic.

Finally, on the session test case page, a little note should be added if the session is the group's default session:
![image](https://user-images.githubusercontent.com/1517675/103802473-17600180-5047-11eb-8f1f-e0e4084d5789.png)

The URLs listed below should accordingly be changed to use the group format as well.

**Comment by cjol** [comment]
Extension task: think about how this might work for corridor testing, where a platform operator wants to test the end-to-end interaction between multiple DFSPs. Intuitively I would have expected each DFSP to be set up in their own group, but with this setup I think the best we can do is to create a new group for the corridor test, containing users from both DFSPs.

**Comment by agalaguz** [comment]
Hi Christopher, @cjol 
We've got some controversial thing in this task and hope you can assist us with it.
It is related to Environment variables that can be set for the session or taken from group env.

If the Default session creator is a member of 

- single group (e.g. Vodafone) - only [sets of variables of that single group](http://prntscr.com/xg9pbu) to be shown during the session creation steps
- multiple groups (e.g. Vodafone and MTN) and makes this session as default for both groups - sets of variables of both groups to be shown there? so, if the Default session creator selects a set of variables that belongs to Vodafone - then MTN group members will see that variables. Is it acceptable behavior, could you please advise?

**Comment by cjol** [comment]
Hi @agalaguz is this an existing issue with the current setup, or is there something new about default groups that makes this a problem? 

As I understand it a member who is part of several groups can already set variables which will be visible for both groups, right? You're right to bring this up, because it is undesirable behaviour ideally - but I don't know if it has a special interaction with the current issue?

**Comment by agalaguz** [comment]
@cjol true, this has no special interaction with the current issue. 
We've only pointed it out during the development/testing of this feature (e.g. when tried to cover all possible test scenarios).

**Comment by dsymonov-jc** [comment]
![index](https://user-images.githubusercontent.com/75664772/105517829-336ad080-5ce0-11eb-9221-46392ae02313.png)

Hi @cjol, can we use "multiselect component" to set groups?

**Comment by cjol** [comment]
@agalaguz regarding the visibility of URLs for sessions which are set by users who are members of multiple groups, let's leave this as accepted behaviour for now. The people who will have access to multiple groups will be "trusted" third parties, who should know better than to set environment variables for the wrong group if/when they edit a session. So I think it's fine.

@dsymonov-jc yes, I think multiselect is a good choice for this situation.
