### ISSUE TITLE
Remove platform Component definitions

### ISSUE THREAD

**Issue by cjol** [gsmainclusivetechlab/interop-test-platform#384]
Now that we use simulators that are driven by the test case, we don't need the simulator URL field that is associated with components. In fact, I don't think we need a centralised concept of "component" at all. Instead, we can derive all the information directly from the test cases.

## Requirements
1. The `components` field of the test case YAML should be modified so that it must take a list of objects instead of strings. The object should contain:
	- A `name` field which indicates the name of a component (as the string currently does). This is displayed to the user.
	- A `slug` field which is a url-friendly version of the name. This is used instead of the component uuid in the SUT urls.
2. Within a test case step, the `source` and `target` fields will now be a slug matching the definition within the `components` section above. 
3. The previous `testing/{session-uuid}/{from-uuid}/{to-uuid}/sut/path` url structure should change to `testing/{from-slug}/{to-slug}/{session-uuid}/path` (corresponding to #388). When a request is received, the session can be retrieved using the UUID. Test cases should then be matched by comparing the `from` and `to` slugs to the `source` and `target` definitions inside the test case steps, instead of using component UUIDs.
3. On the test case page, we no longer generate a connection diagram using a central "connections" table. Instead we can examine the test case steps to extract all the connections at runtime to draw the diagram.
4. All components can be SUTs (so we don't need the "can be SUT" field of the component table). Some SUTs should not be user-editable, which is handled by #352.
5. When creating a new session, the first step should be test case selection (or questionnaire). After the user has selected test cases, we can infer all components involved and generate a system diagram (as in point 3. above) as well as a list of possible SUT components for the user to select and provide URLs.

Making these changes allows ITP to be much more dynamic - to create a test case involving an external system, I can just pick a new component name/slug within the test case and start using it. No other system configuration is required.

**Comment by agalaguz** [comment]
Hi Christopher @cjol,

We've started working on this task and a few questions come up. Hope you can assist us with them.
Basically, this behavior related to both, #384 and #297.

So, based on #384 we need to remove the [global components table](http://prntscr.com/y06961) and move this logic on a Test Case level, i.e. all components to be taken from TC as well as component versions (#297). 
This means that the same component in different test cases may get a different **name**/**slug**/**version**. 

_E.g. **Merchant Payment** is a connection of **SP->MMO1->Mojaloop->MMO2**. In two similar TC of this use case SP may be called_:
- _{name: Service Provider, slug: service_provider, version: 1.0} and {name: SP, slug: service_provider, version: 1.0} OR even_
- _{name: Service Provider, slug: service_provider, version: 1.0} and {name: SP, slug: sp, version: v1}_
_Thus, on a Session creation's system diagram more than a [single connection to be shown](http://prntscr.com/y06s3w), and possibly, [more SUT options](http://prntscr.com/y06uh7) than expected to be shown._ 

Maybe, adding some validations on Components name/slug/version can help to avoid such issues?
E.g. 

- version can be in: 1.2345 format only
- if the same 2 components from different TC have the same slug and ver, but different names -> we show only one name on the system diagram 

---

As a separate solution (I know it differs from the initial description of this issue, but just to get an idea), we may leave the Components table like it is, but pre-populate it with new components from TC.

What do you think? Thank you in advance!

**Comment by cjol** [comment]
Yes, if the test case creator does not use the established "standard" then duplicate SUTs will appear. We are giving the test case creators more control here but this does come at a cost - they need to be responsible! I would be happy to add validations to help avoid these situations. Your version restriction may not work however, because different components will have different (external) versioning systems - e.g. some versions may be tagged with alphabetic codes. The second example would be reasonable (only showing one name if the slug and versions are identical). But again, I expect this to be an uncommon scenario - I would consider it a bug in the _test case_ if the creator uses the wrong component name, not a bug in the _test platform_!

If it is easier to leave the components table as-is, then I don't mind. My thought to remove it was because we will be doing so much dynamic analysis (e.g. to generate a connection diagram or a list of SUTs from the user's selected test cases), so I don't know in which circumstances we would still use the table!

**Comment by agalaguz** [comment]
Hi @cjol,
Just wanted to ensure how the TC selection algorithm to be working in total (based on #384 and #297). So, the new steps are:
1. Select Test Cases
2. Select SUT (The list of "candidate" versions is the intersection of all test case component versions - i.e. a version must in appear in every test case for it to be available for selection. If the list of possible versions is empty (i.e. two test cases expect different version ranges for a component), an error should be displayed, asking the user to modify the selected test cases).)
3. Configuration -> variables, groups, etc.

On item 2 it seems for us that validation applies to versions of Components rather than Components themselves (maybe we are missing something). I'll try to describe how it looks like using this example. 

---

**Session creation Step 1** -> I selected the next Test Cases:
- "Merchant Payment 1" (**SP ver 1** required)
- "Merchant Payment 2" (**SP ver 2** required)
- "P2P 1" (no SP at all)

---

**Session creation Step 2**: -> I selected **SP ver 1** as SUT:

**Expected behavior 1:** System notifies me that "Merchant Payment 2" and "P2P 1" needs to be changed because SP is missed as a component in "P2P 1" and has a different version in "Merchant Payment 2"
**Expected behavior 2:** System notifies me that "Merchant Payment 2" needs to be changed because of SP version ("P2P 1" will still be available as no conflict on the version and user will run it like on NO SUT sessions)

Thus, should avoid adding to Session those Test Cases where only SUT version is different? or, in addition to it, also still avoid adding Test Cases, where SUT Component does not exist at all?
Thanks.

**Comment by cjol** [comment]
In your example, we scan through the test cases and identify the following possible components: SP, MMO1, Mojaloop, MMO2. Stepping through each component, we check to see which versions are possible. For SP, we take the intersection of all the version ranges: (`[v1]` and `[v2]`) and get an empty list `[]`. So we immediately display an error saying something like "The test cases you have selected are incompatible." Basically your "Expected Behaviour 2" is correct, except that we show an error before the user even gets to choose a version for the SUT.

To be clear - the user doesn't need to select a component version in most cases. For a simulator, there are no changes based on the version, and for a SUT the user will provide a URL as normal. The only situation they need to select a version is in the case of an implicit SUT, because then we need to retrieve a URL automatically, based on the component version.

Here are some more examples for clarity:

## Example 2
User selects these test cases:
 - "Merchant Payment 1" (SP v1 and v2, MMO1, Mojaloop, MMO2)
 - "Merchant Payment 2" (SP v2 only,  MMO1, Mojaloop, MMO2)
 - "P2P 1" (MMO1, Mojaloop, MMO2)

In this case, when we look at the version ranges for SP, we take the intersection of `[v1, v2]` and `[v2]` and get a single-item list `[v2]`. The user can choose to make SP, MMO1, Mojaloop or MMO2 a SUT. If SP is set up as an implicit SUT, there is only one version they can choose - v2.

## Example 3
User selects these test cases:
 - "Merchant Payment 1" (SP v1 and v2 and v3, MMO1, Mojaloop, MMO2)
 - "P2P 1" (MMO1, Mojaloop, MMO2)

In this case, when we look at the version ranges for SP, we take the intersection of the single list `[v1, v2, v3]`. The user can choose to make SP, MMO1, Mojaloop or MMO2 a SUT. If SP is set up as an implicit SUT, there are three versions they can choose - v1 or v2 or v3.

## Example 4
User selects these test cases:
 - "Merchant Payment 1" (SP, MMO1, Mojaloop, MMO2)
 - "Alien Test Case" (NewComponent1, NewComponent2)

There are no version conflicts, and so the user can choose any of the following components as SUT: SP, MMO1, Mojaloop, MMO2, NewComponent1, NewComponent2. If any component is set up as an implicit SUT, they can choose any of the versions listed in their respective test cases.

**Comment by jc-anajdenov** [comment]
Failed due to Issue ID51 to this part: 'On the test case page, we no longer generate a connection diagram using a central "connections" table. Instead we can examine the test case steps to extract all the connections at runtime to draw the diagram.'
