### ISSUE TITLE
Twig template is not being resolved on UI examples

### ISSUE THREAD

**Issue by brunosmm** [gsmainclusivetechlab/interop-test-platform#397]
If you open the example of requests and responses, you should see an example of the message with the twig syntax resolved.

## Steps to reproduce

1. Open the test case which uses a twig, example: http://gsma-itp-test-control.staging.s8.justcoded.com/sessions/34/test-cases/106/test-steps
2. Click in test steps
3. Select a request/response

## Expected outcome

Should show a JSON example instead of the twig value.

## Actual outcome

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/1554850/105230077-c5e26700-5b5c-11eb-8a1e-d0dc0b97d266.png">

This can be tricky to handle since references to steps will not be there, maybe would need to process each step in order to be possible create the right variables. @cjol good to have your mind on this.

**Comment by cjol** [comment]
Note also that it's sometimes helpful to view the twig template when you're debugging a template to help understand what's going on! Maybe not on the test run page, but at least on the test case creation page we should leave the variables untouched. 

Note also that the cURL function should be updated at the same time - we never will want to include twig variables in there

**Comment by agalaguz** [comment]
Got your point, thank you. We'll play with that closer to the mid/end of the current sprint (once the main commitments are developed). Looks like it should be possible, but some specific conditions may come up.
