### ISSUE TITLE
Message log -> pagination looks broken if too many pages there

### ISSUE THREAD

**Issue by agalaguz** [gsmainclusivetechlab/interop-test-platform#427]
Issue found during work on #410.
Big number of pages look bad 
![image](https://user-images.githubusercontent.com/16337770/106906399-cdca0b80-6705-11eb-9f7b-ab2ddf7ca9d4.png)

Find a better pagination option.

**Comment by dsymonov-jc** [comment]
Thanks for create ticket.
This problem not only for `message log` page. 
I have rebuild `pagination` component for better UI.
![download (1)](https://user-images.githubusercontent.com/75664772/106910565-04098a00-670a-11eb-844b-96c2fdc0dbcf.png)
