### ISSUE TITLE
HTML code in ITP-simulated responses

### ISSUE THREAD

**Issue by agalaguz** [gsmainclusivetechlab/interop-test-platform#443]
I also notice sending the info via postman, it seems we receive a HTML back on the PUT which is strange

e.g. 
![image](https://user-images.githubusercontent.com/16337770/107375247-31cb4600-6af1-11eb-806b-38a52296ee40.png)

**Comment by cjol** [comment]
This sometimes happened to me when nginx incorrectly redirected from HTTP to HTTPS. I have mostly been able to eliminate the error by disabling this redirect.
