### ISSUE TITLE
Automatic refresh prevent user to navigate to another page

### ISSUE THREAD

**Issue by brunosmm** [gsmainclusivetechlab/interop-test-platform#447]
During a test case execution, and the status is processing the user cannot change the page until it finishes or if clicks in the right timing between the requests to check the test case status.

## Steps to reproduce

1. Execute a test case
2. Click in any button once the loading is happening.

## Expected outcome

The user is redirect to the page he choose.
The processing SHOULD not refresh the whole page every time, otherwise make it impossible to use as an SPA. Should only refresh the vue components related to the re-loading, like steps status and the current step data.

## Actual outcome

If you click once the whole page is loading the action does not happens, since the refresh happens every second is difficult to navigate our the test execution.
In the video you can see I manage to click in the right timing on the last try, but before that was not possible click in the test step:

https://user-images.githubusercontent.com/1554850/107586594-ff981200-6bde-11eb-9dc6-57c91c324347.mov

**Comment by cjol** [comment]
Weird, I can't reproduce this... I thought it was maybe because my internet is fast enough that the "refresh" and the "Test Flow" requests never overlap, but even if I set it to "Slow 3G" it works fine for me
