### ISSUE TITLE
mTLS CSRs

### ISSUE THREAD

**Issue by cjol** [gsmainclusivetechlab/interop-test-platform#453]
The mTLS implementation that we have works well, but I think I made some mistakes in understanding the required functionality. I have spelled out the diferences by annotating some notes below:

In these annotated notes:
 - Black is the "normal" mTLS behaviour
 - Blue is the behaviour currently implemented
 - Orange is where our implementation differs from our users' expectation

![image](https://user-images.githubusercontent.com/1517675/107807553-35183900-6d60-11eb-8a70-afa5f342406e.png)
![image](https://user-images.githubusercontent.com/1517675/107806028-1f097900-6d5e-11eb-834b-857926344b63.png)

To match our users' expectations then, I think we need to do three things (in my estimated order of difficulty):

## ~1. Separate "frontend" and "testing" routes in nginx~
~We have three situations:~
 - ~"Frontend" routes, which should be served over HTTPS using LetsEncrypt certificates in production (or self-signed localhost certificates in development)~
 - ~"/testing-insecure" routes, which shouold be served over unencrypted HTTP~
 - ~"/testing" routes, which should be served using an encrypted mTLS connection.~

~I might be wrong, but I think right now the HTTPS for frontend and the mTLS routes use the same server block, which might make it difficult for us to use different server certificates in the two cases. In the "/testing" path, we will want to start using our own server key, self-signed by RootCA (see below).~

## 2. Generate client keys ourselves

In the form where users currently can upload a private key, cert and CA cert, it would be more secure for us to generate our own private key (otherwise someone else has a copy of our server key). The way I imagine this working is that we have a button to "create new key". When the user clicks it, we create a new key and a CSR inside the certificates table. The CSR is given to the user to download, and the user can then upload a signed certificate which we add to the certificates table. When we make a request to the SUT, we use the key that we generated, and the certificate that they uploaded. Note that it might take the user some time (maybe days) to generate the certificate, so it should be possible to have a "partially complete" certificate set without the client cert, and the user can return later to add it. If the user runs the test case before uploading the cert, then the request will fail and that's okay (it would be good if we can return a custom error saying "No client certificate has been uploaded").

## 3. Provide an interface for ITP to sign CSRs
Currently, we get SUTs to self-sign their client certificates. It would be more secure if we signed the certificates, so we need to provide some kind of interface for users to upload a CSR. ITP should then return a certificate signed by RootCA, which the user can install inside their SUT. Nginx will then receive requests from the SUT accompanied by this certificate, which we can validate using RootCA.

This does not need to be attached to a session, and the results do not need to be stored anywhere so I think the function can be stateless.

I _think_ this means that we don't need the script that regenerates ClientCA anymore.

I am very unsure if I have understood everything correctly, so I would appreciate any feedback if you think I have got anything wrong (or indeed if you think I've got it right, I would appreciate a 👍!)

**Comment by KolyaSirik** [comment]
Hi Christopher @cjol ,

1 - Now we have same behavior. For "/testing" routes we are using our own server key, self-signed by RootCA.
2 and 3 - Currently we have functionality for generation client certificates in the platform signed by RootCA - "Download certificates" button. We can add same button to the form where users can upload certificates

**Comment by cjol** [comment]
That's great, thank you for confirming. The reason I thought 1 might be needed is because of this:
![image](https://user-images.githubusercontent.com/1517675/107970357-ec9f8c00-6fa8-11eb-9b9a-8572c6c3dba0.png)
Note that the certificate is "issued by" R3 - so I think it is using the letsencrypt server key right? However, this is on a custom deployment where we have slightly modified the nginx config so it's possible that I've made a mistake in configuring it there.

For 2 and 3, it's good to hear that it won't be too big a change to add an upload button.

**Comment by agalaguz** [comment]
Hi Christopher @cjol,
Please find below our ideas/suggestions:

1) "Generate client keys ourselves" and "Provide an interface for ITP to sign CSRs" - on the Secure session page we basically generate the set of RootCA.crt, client.crt and client.key that SUT can use to send messages to ITP (This is a "Download certificates" button). So, in order to share this function to SUT, so they don't need to generate anything by themselves - we may add this button to the session creation steps (e.g. the SUT selection/configuration step) 
![image](https://user-images.githubusercontent.com/16337770/112117919-8966d200-8bc4-11eb-8518-cd5214f0b65a.png)
 where the user instead of just uploading own crts and key will be able to download ITP generated ones and use them - i.e. upload them back to the session. 

2) Other UI/UX implications - if user may not be ready to upload crts and a key during the session creation, we should allow him to do it on session edit screen and also add some notice (that some crt or key a still required) on the session page. Or user may just disble encryption and enable it later on session edit page.

Could you please let me know if this makes sense?

**Comment by cjol** [comment]
Hi Anton, thanks for starting the design work on this. The big difference is that we need to involve certificate-signing requests (CSR) in both cases. This allows the key owner to keep their key private while nonetheless getting a signed public certificate from the other party.

We need to do this in both directions.
1. ITP needs to generate a private key, and then share a CSR with the SUT. The SUT will sign the CSR and upload the resulting certificate to ITP. ITP will then use its private key and the uploaded certificates to make outgoing requests to the SUT.
2. SUT needs to generate a private key, and share a CSR with ITP. ITP will sign the CSR and make the certificates available to the SUT. The SUT will then use its private key and the downloaded certificates to make incoming requests to ITP. 

Direction 2 is quite easy, because our code already generates a CSR internally (in the code that powers the "Download Certificates" button):
https://github.com/gsmainclusivetechlab/interop-test-platform/blob/06ef60a3da9baf0c23f44ffe8464467aefe7495c/src/app/Http/Controllers/Sessions/CertificatesController.php#L28-L34
We just need to let the client upload the CSR themselves instead of generating a fresh one.

Direction 1 is slightly more complicated. We first need to generate a private key, and a corresponding CSR (like we currently do in the code snippet above). Thinking about it, it would be acceptable to use the same private key and CSR across all sessions - so we could generate this once by hand instead of writing code to do it. Then in the "upload certificates" form, we need to add a button labelled "Download CSR". Finally, the user will need to upload the Client Certificate (which they generated from the CSR) to the session just like they currently do (and we will remove "Client Key" from the form and use the pregenerated key instead). 

You are right that we can simply allow users to upload their certificates in the session edit screen, so we don't need any special handling for that condition.

**Comment by agalaguz** [comment]
Hi Christopther @cjol, 
Thank you for your comments. 
A few thoughts about the implementation.

**Direction 2** - Add the missed ability for SUT to share own CSR then get certificates that from ITP. 
 
![image](https://user-images.githubusercontent.com/16337770/112311208-23567980-8cae-11eb-99c1-b42530f97e6c.png)
 
 1. User clicks the existing "Download certificates" button and gets a popup where SUT's CSR can be added.
 2. User adds CSR and submitts it.
 3. ITP immediately generates zip file that includes ITP's CA cert and client public cert.

**Direction 1** - Add the missed ability for ITP to share own CSR that SUT can use to generate public cert and upload it.

![image](https://user-images.githubusercontent.com/16337770/112311253-2f423b80-8cae-11eb-92f8-15b0f448e019.png)

1. During the session "creation" (maybe "edit" as well) steps user get an ability to download ITP's CSR.
2. Client cert field remains optional, but some warning to be shown on session pages until public cert is uploaded.

Could you please let me know if this makes sense?

**Comment by cjol** [comment]
Hi Anton, this sounds good. My only comment: 

> some warning to be shown on session pages until public cert is uploaded.

Not all test cases use mTLS, so I think it's probably better not to display a warning. There will be a test failure if they try to execute the test without encryption anyway, so it's probably okay.
