### ISSUE TITLE
Large payloads crash the page

### ISSUE THREAD

**Issue by cjol** [gsmainclusivetechlab/interop-test-platform#466]
When I executed this test case, I got an empty error modal which I didn't take a screenshot of. 

When I refreshed the page, I got this error. Note the body is large - 455 entries which each consists of a deep object.
![image](https://user-images.githubusercontent.com/1517675/108689689-4ba55980-74f1-11eb-89da-f2d58c181cd3.png)

In the case of large payloads, I would consider that it's acceptable not to stringify the JSON. Just display the text as-is to save on computation.

**Comment by brunosmm** [comment]
Adding more info...
The load of the page took 1.3 mins, the transfer was around 5.5mb
![image](https://user-images.githubusercontent.com/1554850/108720043-16076d00-74ff-11eb-9601-2f41106e3404.png)

**Comment by cjol** [comment]
try with account id 35 if you want even worse ;)

**Comment by brunosmm** [comment]
More info about MM Simulator:
![image](https://user-images.githubusercontent.com/1554850/108857207-9eeadb00-75c9-11eb-8a20-73ad5467874d.png)
