### ISSUE TITLE
Upload batch of test cases

### ISSUE THREAD

**Issue by brunosmm** [gsmainclusivetechlab/interop-test-platform#472]
As a test case creator/admin I want to update a batch of test cases at once, which could be via a zip file with the yamls inside or update the import page to be possible to add more than one file per time.
Another option would be add a button to Import and come back to the import page instead the test case page.

Requirements:

Upload more than one test case per time without the need to reopen the upload page.

Open Points:

Decide if is needed and what is the best implementation for it.

**Comment by cjol** [comment]
Relatedly, it would be good to update the TestCaseTableSeeder script so that seeding adds test cases as _versions_ if the test case slug already exists (currently it skips)
