### ISSUE TITLE
Message Log Regex

### ISSUE THREAD

**Issue by cjol** [gsmainclusivetechlab/interop-test-platform#475]
Looks like url sections aren't mathcing properly: 
![image](https://user-images.githubusercontent.com/1517675/109016938-96200500-76ae-11eb-8a7e-71f039c2b560.png)

I don't know yet if this is a problem with the message log or with the underlying matching (the request also failed to match unexpectedly)

**Comment by brunosmm** [comment]
@cjol, would be good to add the test case and the patter you expected to match against it. Will help to debug

**Comment by cjol** [comment]
It's not really to do with any specific test case - it's the regex that powers the "session id", "source component ID" and "target component ID" inside this modal that are wrong. I'll fill in detail later if I can - I'm working on a different issue and just wanted to record the weirdness!

**Comment by brunosmm** [comment]
Ah so it's just a UI problem? cool I thought the test cases was not matching anymore.

**Comment by cjol** [comment]
In this case the test case _also_ didn't match, but I think it's unrelated to the current issue (I think it's related to the curl request that was generated in the Test Steps tab)
