### ISSUE TITLE
Allow exporting any test run as an offline (HTML/PDF) report

### ISSUE THREAD

**Issue by cjol** [gsmainclusivetechlab/interop-test-platform#512]
As a session owner, I want to share my results with other users, who may not be using ITP themselves.

**Comment by agalaguz** [comment]
Our ideas on it:

1. Make just a share link like `{domain}/share/{test-run-uuid}` to the the test run page that the session owner can copy and send to anyone (assuming view only mode) - **around 1-2 days**.  
2. Make import of the simplified version like 
![image](https://user-images.githubusercontent.com/16337770/138445060-e87b67fd-583a-44ee-93c5-efd5ae961f68.png)
 using Dust ([https://laravel.com/docs/8.x/dusk](https://laravel.com/docs/8.x/dusk)) - **around 2 days** to try if it works - we are not sure about it as never tried, but **within 2 days should develop it or understand that this is not possible**.
3. Make import of the simplified version using the assests (css and js files) hosted on the platform domain - **around 1 week**.
4. Make import of the simplified version using the assests added inside the report or as a zip that inludes all html, css, and js (fully offline version that won't need an internet connetion on a PC where the report is used) - **around 2 weeks**.

**Comment by eudisley** [comment]
Hello, @agalaguz 
It seems to be a good approach what you suggest. I think the time is too much for this feature. 2 weeks is a long time comparing to all the deliverables we had in a two weeks sprint in the past. So, please, keep this on hold until we solve other priorities.

**Comment by KisIrene** [comment]
Hello @cesdias  @eudisley 
What approach should we implement?
Please choose an option, from the suggested.

**Comment by cesdias** [comment]
> 

Hello @KisIrene and @agalaguz 
You can procece with approach 2.

I would like to add that as @cjol mentioned the issue #513, I think will be nice to have an API endpoint to export the html test case result other than through interface buttons.

**Comment by KisIrene** [comment]
@eudisley  @cesdias @SamyBouch 

Working on the investigation of obtaining a test run result we encountered some difficulties with the implementation through "Dusk". In this case, a passing logged-in user is impossible, JS doesn't work, and styles links are broken.

The main question is: Do you need to get the results of a test run OFFLINE? Or do you need to get the ability to share the results of a test run assuming using an internet connection?

So basically, there is only one option left to get the results offline:
Make import of the simplified version using the assets added inside the report or as a zip that includes all html, css, and js (fully offline version that won't need an internet connection on a PC where the report is used). If it needs to include JS and all the numbers of logs, the file we get in the result may be around 50-150 MB - **approx 2 weeks**.

The most rational option (more preferable, as we think):
Make just a share secure link like {domain}/share/{test-run-uuid} to the test run page that the session owner can copy and send to anyone (assuming view-only mode). - **around 1-2 days**.

If you'd like to make links more secure, it can also proceed in this way  [](https://laravel.com/docs/8.x/urls#signed-urls )

`test-run/{testRun:uuid}/1?signature=ea9abbb4eb52d24c3d853fa64a7125c10529f201712844d21ca5aa56fbcc4e46test-run/{testRun:uuid}/1?signature=ea9abbb4eb52d24c3d853fa64a7125c10529f201712844d21ca5aa56fbcc4e46`


So we need feedback from your side to move on.

**Comment by jc-skushnir** [comment]
I believe that a simple 2-step test run on import, in theory, shouldn't take more than 2MB. Just if the test run will have many steps, with repeats, a large amount of data in requests and responses, openapi validation, etc. then it can be quite large files.

**Comment by cesdias** [comment]
@jc-skushnir could you clarify what is the options for securing the link if we go with that option? I mean, for each test run, will you provide a button like "share this test run"? Can we unshare the link?

**Comment by jc-skushnir** [comment]
@cesdias we can create public route that will be available to the user that not registered on the platform. So platform users could copy that public link and share it with others.
We could make it as simple link like `test-run/{testRun:uuid}/1` or we could make it as `signed` route so it will be more secure and link will looks like this `test-run/{testRun:uuid}/1?signature=ea9abbb4eb52d24c3d853fa64a7125c10529f201712844d21ca5aa56fbcc4e46` (the {testRun:uuid} will looks like this `75f4f38c-daea-4edf-b56c-73f87156ea59`). The `signed` option allows us create expired links (e.g. set expite time throgh platform envs), but for better performance we make each test run step as separate pages so we need to make sure that all steps will be disabled when time has expired (link looks like this `test-run/{testRun:uuid}/1?expires=1638532115&signature=ea9abbb4eb52d24c3d853fa64a7125c10529f201712844d21ca5aa56fbcc4e46`).
If needed, for both options we could implement something like switcher that disable specific test run on public route (by default it could be disabled).

**Comment by cesdias** [comment]
@eudisley @jc-skushnir due to the fact we still have the requirement to export a offline version of the test case results, specially for compliance platform, we are stepping down the sharable link version in favor of a offline report, but now in PDF format.

Now the idea for this feature is to consider the report from the Session's point of view:
1) User access Sessions menu where all sessions associated with that user are displayed.
2) User select a Session and then all the Test Cases associated with that Session are displayed.
3) User has the ability to select the Test Cases he/she wants to export in PDF.
3.1) To select a Test Case, the User must tick a checkbox right beside the Test Case Name
3.2) User can select all Test Cases by ticking a checkbox "Select All Test Cases"
4) User clicks on a button "Export..." to generate the PDF report based on the selected Test Cases.

The formatting of the pages in the PDF is not attached to the exact looking of the ITP platform, so the exported PDF should have a customised page format. To select the format for the pages of the PDF, you should list what the types of formatting are available by the library used to generate PDFs then we will select the formatting template which works best and add any customised text and logos required into this template for you to incorporate.

**Comment by KisIrene** [comment]
Hi @cesdias , hi @eudisley , we've got several questions:

- Do you want the report of Test Cases or Test runs?
- If you need a report of Test Cases, do we need to display only the last test runs? or all of them?
- What kind of information about the test run do you want to include in the report?
- In case you want to display the results of all test runs, do we need the ability to export all test runs?
- Should the report be displayed as a table? If not, how do you want it to look like?
- Should we generate the report at once, by clicking a button? Another option if we make it through the queues, by sending the report via e-mail.
- All the data (request/response) will have a look like a JSON row without a prettifier.

**Comment by eudisley** [comment]
Hello  @KisIrene 

1. Do you want the report of Test Cases or Test runs? 
**Test Cases** 

2. If you need a report of Test Cases, do we need to display only the last test runs? or all of them? 
**The user chose a session to export. Then the user can select which test cases will be exported. When the Test Cases, the user can tick which test runs they want to export. So, it could be all of them.**

3. What kind of information about the test run do you want to include in the report?
    
    - **Introduction about the session being exported, such as: session, date, etc.**
- **Test cases organised by use case and test cases**
    - **Use Case (e.g Merchant Payments)**
        - Test Case 1 Description Pass
            - Step 1 (eg. POST /transactions....)
                - Request {headers} {JSON body}
                - Response {headers} {JSON body}
            - Step 2 (eg. PUT callback....)
                - Request {headers} {JSON body}
                - Response {headers} {JSON body}
        - ...
    
4. In case you want to display the results of all test runs, do we need the ability to export all test runs?
**Answered by the second question**

5. Should the report be displayed as a table? If not, how do you want it to look like?
**We expect suggestions from you about the possibilities you can do using Dusk (or another framework you chose), considering we have good UX for the users to read. In the final version is important that we can customise the header of the file, considering we will have different headers for ITP and Compliance.**

6. Should we generate the report at once, by clicking a button? Another option if we make it through the queues, by sending the report via e-mail.
**We can have a button with the option reports/export/etc. Once the user clicks in the button, the platform would redirect to another page where the user can select the runs they want to export to the final PDF file. After clicking generate the PDF will be automatically downloaded. 
*OBS1: I will share at the end of this answer an initial idea about how this page looks like. 
OBS2: This action should be added into the admin message log (one of the current cards).***

7. All the data (request/response) will have a look like a JSON row without a prettifier.
    
    **The report will have two versions. One with the JSON (named Technical) and another without (called Business). This option will be available in the page where the user selects the parameters to generate the report.**

-------

**Draft idea about how the user interact with the report page.
It is important to think how to provide this page with good UI/UX**

1. User clicks **Export results**
2. **Exporting Page** is opened
3. User select the **type of report**: | | Simple | | Extended (With a small explanation of each)
4. User **selects the test cases** inside the session **to be exported**:
    1. **Payee/Merchant-Initiated Merchant Payment**
        1. Happy Flow
            1. |  ✓ | Payee-Initiated Pooling - Success
                1. |  ✓ | # Run 723
                2. |  ✓ | # Run 725
                3. |___| # Run 811
            2. |___| Payee-Initiated - Callback - Success
            3. |___| ...
        2. Unhappy Flow
            1. |  ✓ | ...
    2. **General**
        1. Happy Flow
            1. |  ✓ | Test Case 01
            2. |  ✓ | Test Case 02
            3. |___| ...
        2. Unhappy Flow
            1. |___| Test Case 03
            2. |___| Test Case 04
            3. |___| ...
5. User clicks button export/proceed
6. PDF File is generated
