### ISSUE TITLE
Allow triggering test runs via API

### ISSUE THREAD

**Issue by cjol** [gsmainclusivetechlab/interop-test-platform#513]
As a session owner, I want to be able to trigger execution of my test cases programmatically - for example in the context of a CI/CD session.

**Comment by cjol** [comment]
This would ideally also allow access to #512 to generate a run report, which could also be attached to the CI/CD run.

**Comment by agalaguz** [comment]
In order to estimate this task, let's define the high-level algorithm of this procedure.
Getting answers on these questions should help us to move forward.

1. How the test Session per particular CI/CD run should be created? - assuming the Session is configured manually in advance.
2. Session types - secure/insecure, certificates etc.? - assuming the Session is configured manually in advance.
3. How SUT(s) should be configured? -  assuming the Session is configured manually in advance.
4. How Test Cases should be selected per particular session? - assuming the Session is configured manually in advance.
5. How the test Session to be inititated? - run Test Cases one-by-one (not in parallel)
6. How to initiate Test Cases where the SUT is initiator? Just start them and wait until the SUT send the first request?

Assumptions what API can do:
- Get all Test Cases (IDs) of the pre-defined Session (to store them in CI)
- Run Test Case by ID (CI to activate them one-by-one)
- Check status of the Test Case by ID (ensure if all Test Cases)

What do you think?

**Comment by cesdias** [comment]
> In order to estimate this task, let's define the high-level algorithm of this procedure. Getting answers on these questions should help us to move forward.
> 
>     1. How the test Session per particular CI/CD run should be created? - assuming the Session is configured manually in advance.
> 
>     2. Session types - secure/insecure, certificates etc.? - assuming the Session is configured manually in advance.
> 
>     3. How SUT(s) should be configured? -  assuming the Session is configured manually in advance.
> 
>     4. How Test Cases should be selected per particular session? - assuming the Session is configured manually in advance.
> 
>     5. How the test Session to be inititated? - run Test Cases one-by-one (not in parallel)
> 
>     6. How to initiate Test Cases where the SUT is initiator? Just start them and wait until the SUT send the first request?
> 
> 
> Assumptions what API can do:
> 
>     * Get all Test Cases (IDs) of the pre-defined Session (to store them in CI)
> 
>     * Run Test Case by ID (CI to activate them one-by-one)
> 
>     * Check status of the Test Case by ID (ensure if all Test Cases)
> 
> 
> What do you think?

Hi @agalaguz,

1. Input a already created session number to run. Also it's desirable to have the ability to stop the execution.
2. Support both secure and insecure types.
3. We are not sure what this questions means exactly. Could you clarify a bit more?
4. TC IDs should be used for select test cases. 
5. Run test cases one-by-one.
6. Yes. Just start and wait for the request, but with a timeout like 30 seconds.

On assumptions:

* Get all Test Cases (IDs) of the pre-defined Session (to store them in CI)
Agreed. It may return TC IDs as well other informations, like the name and slug of a TC.

* Run Test Case by ID (CI to activate them one-by-one)
Agreed.

* Check status of the Test Case by ID (ensure if all Test Cases)
Agreed, but it's desirable to have the possibility to see status of all test cases at once.

**Comment by jc-skushnir** [comment]
If I get it right, outcome:
manualy created session, that has uuid {sessionUuid}, with assigned test cases

API flow example:
1. GET /api/session/{sessionUuid}/testCase
`
response: 200 [{"id":"1","slug":"testcase1","uuid":"tc1","name":"testcase1"},{"id":"2","slug":"testcase2","uuid":"tc2","name":"testcase2"},{...},{"id":"N","slug":"testcaseN","uuid":"tcN","name":"testcaseN"}]
`
Note: return test cases assigned to session with some additional information.
2. POST /api/session/{sessionUuid}/testCase/{testCaseUuid}/run
`
response: 201 {"id":"1","uuid":"tr1"}
`
Note: return created test run with some additional information.
3. GET /api/session/{sessionUuid}/testRun/{testRunUuid}/status
`
response: 200 {"id":"1","uuid":"tr1"}
`
Note: return created test run information.
4. POST /api/session/{sessionUuid}/testRun/{testRunUuid}/stop
`
response: 200 {"id":"1","uuid":"tr1"}
`
Note: complete test run and return created test run information (need investigate and add additional check, on complete test step before run next step. check is test run completed). or we need just simple route that stops any test run in session if exist, e.g. POST /api/session/{sessionUuid}/stop

Additional questions:

1. how user get information about API routes (examples requests/response, routes, necessary ids, etc)? Should we show some routes on session test case pages (just like SUTs)
2. we can use uuid (session, test case, test run) in routes for more security or just simple ids (session, test run, test case) and slug (test case). in that case do we need some secure check like token?
3. request/response schema (is there some necessary fields in responses and some rules for naming, e.g. response status should contain field "status" with values pass/fail)?
4. what should we return on stop route if all test runs already stopped (e.g. if its by test run id - same test run info, but if we implement "stop" route without test run id - without any information)
5. how do we get status of all test runs at once? could we keep and then pass all test runs ids in POST? e.g.
`
POST /api/session/{sessionUuid}/status
`
`
with payload like: ["testRunUuid1", "testRunUuid2","testRunUuidN"]
`
`
response: 200 [{"id":"1","uuid":"tr1","status":"pass"},{...},{"id":"2","uuid":"tr2","status":"fail"}]
`
or somehow set time in seconds and search all test runs that has been created in that range? example
`
POST /api/session/{sessionUuid}/status/{timeInSeconds}
`
`
response: 200 [{"id":"1","uuid":"tr1","status":"pass"},{...},{"id":"2","uuid":"tr2","status":"fail"}]
`
