### ISSUE TITLE
Test Cases rendered in nonalphabetic order

### ISSUE THREAD

**Issue by cjol** [gsmainclusivetechlab/interop-test-platform#520]
If I update a test case, it drops to the bottom of the list. This makes it difficult to find a particular test case, because they are not displayed in a predictable order any more.

**Comment by cesdias** [comment]
@yvoitenko I have updated a few test cases and the result was this:

![image](https://user-images.githubusercontent.com/18514013/159474987-07c59bb7-94c2-4545-8d2a-50251ecf1b1a.png)

The `Version 2` test cases are on the top and are sorted in nonalphabetic order.

**Comment by yvoitenko** [comment]
@cesdias it's fixed by #625
