### ISSUE TITLE
Simulator Plugins

### ISSUE THREAD

**Issue by cjol** [gsmainclusivetechlab/interop-test-platform#537]
This task is an extension/modification of #528.

Some users of the platform may need to modify requests made by the simulator before they are made. For example, they may wish to add an `Authorization` header, which is not defined inside the test case. 

Currently, this is possible in a limited way, if the test case author adds logic to the test case to handle this customisation. As a generic alternative, we could allow arbitrary modifications to be applied to a request/response based on a JavaScript "plugin" file uploaded to the user group. As an example, a test case could be defined like this:

```yaml
slug: 'my_test_case'
test_steps:
  - request: 
      method: POST
      uri: /biscuits
      headers:
        Accept: 'application/json'
        Content-Type: 'application/json'
      body: 
        biscuits:
           - { name: Digestive }
           - { name: Choco Leibniz }
```

A platform administrator would be able to upload a JavaScript "plugin" script to the user group* looking like this:

```js
module.exports = function(step, type, test_case) {
    if (type === "request") {
        const request = step.request;
        if (test_case === "my_test_case" && type === "request" && step.source === "api-client") {
            delete request.headers.Accept;
            request.headers.Authorization = "my-super-secret-auth-token";
            request.body.biscuits = request.body.biscuits.map(b => b.name === "Digestive" ? ({
                ...b,
                name: "Hobnob"
            }) : b);
            request.body.biscuits.push({
                name: 'Party Rings'
            });
        }

        return request;
    } else {
        return step.response;
    }
}
```

When a test session is created or edited, the user should be allowed to select one of the plugin scripts previously uploaded to a group he is a member of. If he selects a plugin, the test platform will invoke the plugin script every time a simulated request/response is generated. The parameters passed to the JS function should be:
- `step`: The currently-executing test step as defined in the test case (after Twig processing)
  - An additional property called `iteration_count` should be added, corresponding to the number of repetitions of the test step in a `repeat`ed step (should be `1` if the step is not repeated)
- `type`: Either `"request"` or `"response"` 
- `testcase`: The matched test case slug
- `env`: The current session environment (string variables only)

There are multiple ways we could execute this JavaScript, and I do not have a preference about which one we explore. Some options would be to install the [v8 PHP extension](https://www.php.net/manual/en/book.v8js.php), or to run Node in a separate docker container, accessible over an HTTP endpoint. Whatever is easiest for now (in future we may revisit this to ensure the solution is sufficiently secure for arbitrary code execution).

The value returned by the JS function should be interpreted as a request or response as appropriate, and passed onwards to the next step (e.g. stored in the database and forwarded to a SUT). This would result result in the following example request being sent

```
POST /biscuits
Content-Type: application/json
Authorization: my-super-secret-auth-token

{ "biscuits": [ {"name": "Hobnob"}, {"name": "Choco Leibniz"}, {"name": "Party Rings"} ] }
```

Note that this approach does allow the session owner to change anything about the requests being made by the simulator - which is a powerful tool, but may also lead to a test case execution deviating from the intended specification. When this happens, however, the test case assertions should nonetheless indicate that the request is malformed, and display a failure.

---
* Control over the plugins should be limited to platform administrators for now, but will likely be relaxed to group administrators in future. Before we do that, we will need to ensure that the execution of plugin scripts is sufficiently "sandboxed" (e.g. in a separate Docker container) to allow unsupervised execution.

**Comment by agalaguz** [comment]
Examples of script file and test case are [here](https://drive.google.com/drive/folders/1_rZSCC7teH43HRkPagSQK7F2gxiu26oz?usp=sharing).
A short info about objects used in this feature is [here](https://docs.google.com/document/d/1oSQHv5X_9eYXDicvoRMxRUQLWLoKRXMSoiTy2iCnT58/edit?usp=sharing).
