### ISSUE TITLE
Enquire about ITP test run timeout

### ISSUE THREAD

**Issue by SamyBouch** [gsmainclusivetechlab/interop-test-platform#554]
As far as we know the timeout for a test run waiting to receive a request is 30 seconds. Ideally there should be a simple way to change this for debugging purposes.

**Comment by jc-skushnir** [comment]
@SamyBouch in config file [service.env](https://github.com/gsmainclusivetechlab/interop-test-platform/blob/develop/service.example.env) we got configs like
```
# How long should a test run wait for the first message to be sent
TESTRUN_INITIAL_TIMEOUT=300
# How long should a test run wait for subsequent messages to be sent
TESTRUN_STEP_TIMEOUT=30
# How often to check if a test run is complete
TESTRUN_TIMEOUT_FREQUENCY=30
```
i.g. on test case run we set **TESTRUN_TIMEOUT_FREQUENCY** and check test run status every **TESTRUN_TIMEOUT_FREQUENCY** seconds. Test run completes when:

- test run has entries (test result) and this test result created earlier than **TESTRUN_STEP_TIMEOUT** seconds ago
- test run has no entries (test result) and this test run created earlier than **TESTRUN_INITIAL_TIMEOUT** seconds ago

In other way we wait one more time **TESTRUN_TIMEOUT_FREQUENCY** seconds and check test run again in the same way.

Hope that was helpfull.

**Comment by eudisley** [comment]
@SamyBouch I am closing this card since you already test, right?

**Comment by SamyBouch** [comment]
@eudisley Yes I was able to change the timeout with these parameters.
