### ISSUE TITLE
Enable/Disable ITP Features

### ISSUE THREAD

**Issue by SamyBouch** [gsmainclusivetechlab/interop-test-platform#555]
As more features are implemented into the project, we currently have to keep different branches for the different releases (ITP,Compliance etc) so as to not include unwanted features. However this might lead to issues in the future so it would be nice if there was a way to enable or disable features (such as Simulator Plugin, FAQ section etc) before running the platform, so that all releases can use the same branch.

**Comment by agalaguz** [comment]
We think that the best option to configure this under `.env` file, as makind this through the UI would add a bit level of complexity. 
However, let's break down project on features prior to estimating this task as depending on "feature" definitions we may check code and understand how easy they are to be switched on/off. (e.g. hiding FAQ section may take much less time than hiding Complience session, if we are talking about something more than hiding the related buttons)

Can you please make a list of the features that are required right now and some that may be required soon, so we investigate them deeper?

**Comment by eudisley** [comment]
Hi @agalaguz 
I agree with you, and I think the enable/disable features functionality should be using a .env file. I also think this was Samy idea initially. I will ask @SamyBouch  and @cesdias to make a list of these features here, so it would make easier to estimate.

**Comment by SamyBouch** [comment]
Hi @agalaguz, for now the only features we would like to enable/disable are the "Simulator Plugin" and "FAQ" features.
