### ISSUE TITLE
Test Run - Undefined Index: Status

### ISSUE THREAD

**Issue by eudisley** [gsmainclusivetechlab/interop-test-platform#575]
This is an error from one of our partners. They are using the compliance platform to validate their use cases/test cases. Most of the tests are going well, but they have found an error, and we do not know what it might be. 

The Test Case they are getting the problem is 
**_Payer-initiated (debitParty and creditParty sent) - callback - success_**

The error can be seen by Anton (who has admin access) [here](https://compliance.mobilemoneyapi.io/sessions/98/test-cases/579/test-runs/1762/2)

I am pasting a print screen of the error: 
_**Pending
Undefined index: status**_

![Screenshot 2021-11-25 at 14 57 39](https://user-images.githubusercontent.com/4050924/143463451-d4691185-0c96-4c19-a418-78939ab74cfe.png)

## Details
Unfortunately we're not able to reproduce this bug consistently, but it seems this was happening only in certain sessions. When the same callback request was sent to a new session, the error did not occur.

There was a simulator plugin attached to the session, which I have attached in case it is relevant.
[bulk_plugin.js.zip](https://github.com/gsmainclusivetechlab/interop-test-platform/files/7602760/bulk_plugin.js.zip)

**Comment by jc-skushnir** [comment]
@eudisley Please check the **simulator plugin**. It should always return a request or response depending on the **type**. In the simulator plugin attached to this issue, I can see that it returns a request anyway. It can be fixed as follows: 
```
module.exports = function(step, type, test_case, env) {
	const request = step.request;
	const response = step.response;

	if (type === "request") {
		if (request.path === "/batchtransactions") {
			/* 1) Add additional parameters to body */  
			request.body = {
				...request.body,
				batchTitle: "Test Title",
				batchDescription: "Test Description",
				scheduledStartDate: "2021-10-20T10:36:50+00:00",
			}
		} else {
			return request;
		}
	} else {
		return response;
	}
}
```
Please let me know if this makes sense.

**Comment by SamyBouch** [comment]
@jc-skushnir I haven't been able to test and confirm this yet but to me this makes sense, as this error only occurred in sessions which had this simulator plugin. But I will double check just to be sure

**Comment by KisIrene** [comment]
> @jc-skushnir I haven't been able to test and confirm this yet but to me this makes sense, as this error only occurred in sessions which had this simulator plugin. But I will double check just to be sure

Ok, please let us know as soon as you check

**Comment by cesdias** [comment]
@KisIrene It was confirmed the issue with the plugin code.
