### ISSUE TITLE
Test case update (using incorerct syntax) created 500 error 

### ISSUE THREAD

**Issue by Viji-GSMA** [gsmainclusivetechlab/interop-test-platform#629]
High-level summary of the problem.
When attempting to update 1 specific  test case using the test case edit UI by admin user , adding (presumably) incorrect syntax has completely broken access to the test cases page instead of just giving an error noting the specific test case cannot be updated

## Steps to reproduce

1. Edit a test case using the test case edit UI
2. Add incorrect syntax to an expected test case body
3. Trying to access test cases page https://compliance.mobilemoneyapi.io/admin/test-cases to reverse the change causes error so no way to edit the test case back to original

## Expected outcome

After steps 1 and 2 if syntax is not correct, error message should be shown that test case cannot be updated and admin should be able to cancel the update and have access to the https://compliance.mobilemoneyapi.io/admin/test-cases page as normal

## Actual outcome

Tying to access test cases page https://compliance.mobilemoneyapi.io/admin/test-cases to reverse the change causes error
500 Oops...You just found an error page  We are sorry but your request contains bad syntax and cannot be fulfilled.

**Comment by KisIrene** [comment]
@Viji-GSMA  **Add incorrect syntax to an expected test case body**
Please explain it in more detail and provide some examples.

Could you specify, please? What exactly the wrong syntax did you use?

**Comment by Viji-GSMA** [comment]
HI @KisIrene I'm not sure exactly what I did wrong - it may well have been incorrect syntax - but in a way that is irrelevant - the point is whatever the error, the admin should just get an error message and be unable to update the test case (regardless of the exact error)

Instead I just receive this page   https://compliance.mobilemoneyapi.io/admin/test-cases with the 500 error when I try to go back to admin>test cases

As noted above this does not enable me to go back into the test case and edit it

This should clearly not happen

**Comment by cesdias** [comment]
Fixed in 9732df39bb2c2e8270854998023388d2ed09b859.
